# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_medicine_lay.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from clickableFrame import ClickableFrame
from database import ConnectionPool,showAllMeds,addMedData,updtMedData,deleteMedData
from EntryChecking import *

class MedDataRetrievalThread(QtCore.QThread):
    dataRetrieved = QtCore.pyqtSignal(object)
    retrievalComplete = QtCore.pyqtSignal()
    def __init__(self, parent=None):
        super(MedDataRetrievalThread, self).__init__(parent)

    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                data = showAllMeds(pool)
                self.dataRetrieved.emit(data)
        except Exception as e:
            print(e)

class AddUpdateDelMedDataThread(QtCore.QThread):
    operationComplete = QtCore.pyqtSignal()
    def __init__(self,data,flag,parent=None):
        super(AddUpdateDelMedDataThread, self).__init__(parent)
        self.flag=flag
        self.data=data
    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                if(self.flag==1):
                     addMedData(pool,self.data)
                elif(self.flag==2):
                     updtMedData(pool,self.data)
                elif(self.flag==3):
                     deleteMedData(pool,self.data)
                self.operationComplete.emit()

        except Exception as e:
            print(e)

class Admin_meds(object):
    
    def __init__(self):
        self.tableMedsDet = QtWidgets.QTableWidget()
        self.medIdEntry = QtWidgets.QTextEdit()
        self.medNameEntry = QtWidgets.QTextEdit()
        self.medStatusEntry = QtWidgets.QTextEdit()
        self.medQtyAvailEntry = QtWidgets.QTextEdit()
        self.medCostEntry = QtWidgets.QTextEdit()
        self.med_data_thread = MedDataRetrievalThread()
        self.med_data_thread.dataRetrieved.connect(self.updateMedTable)
        self.med_data_thread.start()
    
    def backHome(self):
        from Admin_homepage_lay import Admin_home_lay
        self.window = QtWidgets.QMainWindow()
        self.ui = Admin_home_lay()
        self.ui.setupUi(self.window)
        self.window.show()
        self.admin_activity.close()

    def updateMedTable(self,data):
        self.med_data_thread.retrievalComplete.connect(self.med_data_thread.quit)
        for row_number, row_data in enumerate(data):
            self.tableMedsDet.insertRow(row_number)
            for column_number, column_data in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(column_data))
                self.tableMedsDet.setItem(row_number, column_number, item)    

    def showWarningMessage(self,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle("Warning")
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def verifyData(self,data):
        if not checkEmptyFields(data):
                self.showWarningMessage("All Fields are mandatory!!")
        else:
                if checkLicenseNumber(self.medIdEntry.toPlainText().strip(),self.tableMedsDet):
                    if  (checkNumericWith0(self.medQtyAvailEntry.toPlainText().strip()) and checkNumericalData(self.medCostEntry.toPlainText().strip()) and checkNumericalData(self.medIdEntry.toPlainText().strip()))==False:
                                self.showWarningMessage("One or more numerical field values wrong!!")
                    else:
                                return True
                else:
                        self.showWarningMessage("med id number already in use!!")
        return False
    
    def addData(self):
        data = (self.medIdEntry.toPlainText().strip(),self.medNameEntry.toPlainText().strip(),
                 self.medStatusEntry.toPlainText().strip(),self.medQtyAvailEntry.toPlainText().strip(),
                 self.medCostEntry.toPlainText().strip())
        if self.verifyData(data):
             self.med_add_updt_del_thread = AddUpdateDelMedDataThread(data,flag=1)
             self.med_add_updt_del_thread.start()
             self.med_add_updt_del_thread.operationComplete.connect(self.refreshTable)
        else:
             self.showWarningMessage("Operation failed!!")

    def verifyUpdtData(self,data):
        if not checkEmptyFields(data):
                self.showWarningMessage("All Fields are mandatory!!")
        else:
                if not checkLicenseNumber(self.medIdEntry.toPlainText().strip(),self.tableMedsDet):
                    row = getSelectedRowData(self.tableMedsDet)
                    if row is not None:
                        if str(data[0]) == str(row[0]):
                                print(str(row[0])==str(data[0]))
                                if  (checkNumericWith0(self.medQtyAvailEntry.toPlainText().strip()) and checkNumericalData(self.medCostEntry.toPlainText().strip()) and checkNumericalData(self.medIdEntry.toPlainText().strip()))==False:
                                                self.showWarningMessage("One or more numerical field values wrong!!")
                                else:
                                        return True
                    else:
                        self.showWarningMessage("No row selected!!")  
                else:
                        self.showWarningMessage("med id number already in use or invalid!!")

    def updtData(self):
        data = (self.medIdEntry.toPlainText().strip(),self.medNameEntry.toPlainText().strip(),
                 self.medStatusEntry.toPlainText().strip(),self.medQtyAvailEntry.toPlainText().strip(),
                 self.medCostEntry.toPlainText().strip())
        if self.verifyUpdtData(data):
                data = (self.medIdEntry.toPlainText().strip(),self.medNameEntry.toPlainText().strip(),
                self.medStatusEntry.toPlainText().strip(),self.medQtyAvailEntry.toPlainText().strip(),
                self.medCostEntry.toPlainText().strip(),self.medIdEntry.toPlainText().strip())
                self.med_add_updt_del_thread = AddUpdateDelMedDataThread(data,flag=2)
                self.med_add_updt_del_thread.start()
                self.med_add_updt_del_thread.operationComplete.connect(self.refreshTable)
        else:
                self.showWarningMessage("Operation failed!!")
    
    def delData(self):
        row = getSelectedRowData(self.tableMedsDet)
        if row is not None:
                selected_id_no = row[0]
                self.med_add_updt_del_thread = AddUpdateDelMedDataThread(selected_id_no,flag=3)
                self.med_add_updt_del_thread.start()
                self.med_add_updt_del_thread.operationComplete.connect(self.refreshTable)
        else:
             self.showWarningMessage("Please select record!!")

    def refreshTable(self):
        self.tableMedsDet.clearContents()
        self.tableMedsDet.setRowCount(0)
        self.med_data_thread = MedDataRetrievalThread()
        self.med_data_thread.dataRetrieved.connect(self.updateMedTable)
        self.med_data_thread.start()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 701)
        MainWindow.showMaximized()
        self.admin_activity = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_frame.sizePolicy().hasHeightForWidth())
        self.header_frame.setSizePolicy(sizePolicy)
        self.header_frame.setMinimumSize(QtCore.QSize(1280, 100))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.header_frame.setStyleSheet("background-color:rgb(0, 85, 127);")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_frame = ClickableFrame(self.header_frame)
        self.logo_frame.setMinimumSize(QtCore.QSize(80, 50))
        self.logo_frame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.logo_frame.setStyleSheet("background-color:transparent;\n"
"margin-top:6px;\n"
"margin-bottom:0px;")
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.logo_frame.clicked.connect(self.backHome)
        self.backBtn = QtWidgets.QLabel(self.logo_frame)
        self.backBtn.setGeometry(QtCore.QRect(20, 10, 61, 71))
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backBtn.setStyleSheet("")
        self.backBtn.setText("")
        self.backBtn.setPixmap(QtGui.QPixmap(":/reosurces_logo/back-svgrepo-com.svg"))
        self.backBtn.setScaledContents(True)
        self.backBtn.setAlignment(QtCore.Qt.AlignCenter)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.logo_frame)
        self.title_frame = QtWidgets.QFrame(self.header_frame)
        self.title_frame.setMinimumSize(QtCore.QSize(1280, 0))
        font = QtGui.QFont()
        font.setPointSize(42)
        self.title_frame.setFont(font)
        self.title_frame.setStyleSheet("background-color:transparent;")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.title_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setMinimumSize(QtCore.QSize(800, 0))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color:#fff;")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.title_frame)
        self.verticalLayout_2.addWidget(self.header_frame)
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.activityNameDisp = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.activityNameDisp.setFont(font)
        self.activityNameDisp.setStyleSheet("color:rgb(0, 85, 127);")
        self.activityNameDisp.setObjectName("activityNameDisp")
        self.verticalLayout_22.addWidget(self.activityNameDisp, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(15, 9, 15, -1)
        self.gridLayout_2.setHorizontalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("BACKGROUND-COLOR:#c8cbcf;\n"
"BORDER-RADIUS:5PX;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("padding-right:2px;\n"
"padding-left:2px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setHorizontalSpacing(25)
        self.gridLayout.setObjectName("gridLayout")
        self.medIdEntry = QtWidgets.QTextEdit(self.frame_5)
        self.medIdEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.medIdEntry.setFont(font)
        self.medIdEntry.setStyleSheet("background-color:white;")
        self.medIdEntry.setObjectName("medIdEntry")
        self.gridLayout.addWidget(self.medIdEntry, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.medQtyAvailEntry = QtWidgets.QTextEdit(self.frame_5)
        self.medQtyAvailEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.medQtyAvailEntry.setFont(font)
        self.medQtyAvailEntry.setStyleSheet("background-color:white;")
        self.medQtyAvailEntry.setObjectName("medQtyAvailEntry")
        self.gridLayout.addWidget(self.medQtyAvailEntry, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.medCostEntry = QtWidgets.QTextEdit(self.frame_5)
        self.medCostEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.medCostEntry.setFont(font)
        self.medCostEntry.setStyleSheet("background-color:white;")
        self.medCostEntry.setObjectName("medCostEntry")
        self.gridLayout.addWidget(self.medCostEntry, 3, 1, 1, 1)
        self.medNameEntry = QtWidgets.QTextEdit(self.frame_5)
        self.medNameEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.medNameEntry.setFont(font)
        self.medNameEntry.setStyleSheet("background-color:white;")
        self.medNameEntry.setObjectName("medNameEntry")
        self.gridLayout.addWidget(self.medNameEntry, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.medStatusEntry = QtWidgets.QTextEdit(self.frame_5)
        self.medStatusEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.medStatusEntry.setFont(font)
        self.medStatusEntry.setStyleSheet("background-color:white;")
        self.medStatusEntry.setObjectName("medStatusEntry")
        self.gridLayout.addWidget(self.medStatusEntry, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.gridLayout_2.addWidget(self.frame_3, 0, 1, 1, 2)
        self.delMedBtn = QtWidgets.QPushButton(self.frame)
        self.delMedBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delMedBtn.setFont(font)
        self.delMedBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delMedBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.delMedBtn.setObjectName("delMedBtn")
        self.gridLayout_2.addWidget(self.delMedBtn, 2, 1, 1, 2)
        self.addMedBtn = QtWidgets.QPushButton(self.frame)
        self.addMedBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addMedBtn.setFont(font)
        self.addMedBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addMedBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.addMedBtn.setObjectName("addMedBtn")
        self.gridLayout_2.addWidget(self.addMedBtn, 1, 1, 1, 1)
        self.tableMedsDet = QtWidgets.QTableWidget(self.frame)
        self.tableMedsDet.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableMedsDet.setFont(font)
        self.tableMedsDet.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableMedsDet.setStyleSheet("QHeaderView::section {\n"
"                background-color: #00557d;\n"
"                color: white;\n"
"                font-weight: bold;\n"
"padding:5px;\n"
"            }")
        self.tableMedsDet.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableMedsDet.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableMedsDet.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableMedsDet.setShowGrid(True)
        self.tableMedsDet.setWordWrap(False)
        self.tableMedsDet.setObjectName("tableMedsDet")
        self.tableMedsDet.setColumnCount(5)
        self.tableMedsDet.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 85, 125))
        self.tableMedsDet.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMedsDet.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMedsDet.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMedsDet.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMedsDet.setHorizontalHeaderItem(4, item)
        self.tableMedsDet.horizontalHeader().setCascadingSectionResizes(True)
        self.tableMedsDet.horizontalHeader().setDefaultSectionSize(180)
        self.tableMedsDet.verticalHeader().setDefaultSectionSize(45)
        self.gridLayout_2.addWidget(self.tableMedsDet, 0, 0, 3, 1)
        self.updateMedBtn = QtWidgets.QPushButton(self.frame)
        self.updateMedBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateMedBtn.setFont(font)
        self.updateMedBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updateMedBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.updateMedBtn.setObjectName("updateMedBtn")
        self.gridLayout_2.addWidget(self.updateMedBtn, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)

        self.addMedBtn.clicked.connect(self.addData)
        self.updateMedBtn.clicked.connect(self.updtData)
        self.delMedBtn.clicked.connect(self.delData)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "HOSPITAL MANAGEMENT SYSTEM"))
        self.activityNameDisp.setText(_translate("MainWindow", "MEDICINE"))
        self.label.setText(_translate("MainWindow", "MEDICINE FORM"))
        self.label_7.setText(_translate("MainWindow", "COST:"))
        self.label_5.setText(_translate("MainWindow", "QTY AVAILABLE:"))
        self.label_4.setText(_translate("MainWindow", "STATUS:"))
        self.label_2.setText(_translate("MainWindow", "MEDICINE ID:"))
        self.label_3.setText(_translate("MainWindow", "NAME :"))
        self.delMedBtn.setText(_translate("MainWindow", "DELETE"))
        self.addMedBtn.setText(_translate("MainWindow", "ADD"))
        self.tableMedsDet.setSortingEnabled(True)
        item = self.tableMedsDet.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "MEDICINE ID"))
        item = self.tableMedsDet.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.tableMedsDet.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "STATUS"))
        item = self.tableMedsDet.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "QTY AVAILABLE"))
        item = self.tableMedsDet.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "COST"))
        self.updateMedBtn.setText(_translate("MainWindow", "UPDATE"))
import resources_rc
