# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_patients_lay.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from clickableFrame import ClickableFrame
from EntryChecking import *
from database import ConnectionPool,showPatientsData,addPatientData,updtPatientData,deletePatData
from utils import getSelectedRowData

class PatDataRetrievalThread(QtCore.QThread):
    dataRetrieved = QtCore.pyqtSignal(object)
    retrievalComplete = QtCore.pyqtSignal()
    def __init__(self, parent=None):
        super(PatDataRetrievalThread, self).__init__(parent)

    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                data = showPatientsData(pool)
                self.dataRetrieved.emit(data)
        except Exception as e:
            print(e)

class AddUpdateDelDeptDataThread(QtCore.QThread):
    operationComplete = QtCore.pyqtSignal()
    def __init__(self,data,flag,add_flag,parent=None):
        super(AddUpdateDelDeptDataThread, self).__init__(parent)
        self.flag=flag
        self.add_flag = add_flag
        self.data=data
    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                if(self.flag==1):
                     addPatientData(pool,self.data,self.add_flag)
                elif(self.flag==2):
                     updtPatientData(pool,self.data,self.add_flag)
                elif(self.flag==3):
                     deletePatData(pool,self.data)
                self.operationComplete.emit()
        
        except Exception as e:
            print(e)

class Admin_patients(object):
    
    def __init__(self):
        self.tablePatsDet = QtWidgets.QTableWidget()
        self.pat_data_thread = PatDataRetrievalThread()
        self.pat_data_thread.dataRetrieved.connect(self.updatePatTable)
        self.pat_data_thread.start()
    
    def backHome(self):
        from Admin_homepage_lay import Admin_home_lay
        self.window = QtWidgets.QMainWindow()
        self.ui = Admin_home_lay()
        self.ui.setupUi(self.window)
        self.window.show()
        self.admin_activity.close()

    def updatePatTable(self,data):
        self.pat_data_thread.retrievalComplete.connect(self.pat_data_thread.quit)
        for row_number, row_data in enumerate(data):
            self.tablePatsDet.insertRow(row_number)
            for column_number, column_data in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(column_data))
                self.tablePatsDet.setItem(row_number, column_number, item)

    def showWarningMessage(self,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle("Warning")
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def verifyData(self,data):
        emailNotEmpty = checkEmptyFields((self.patEmailEntry.toPlainText().strip(),))
        hiNotEmpty = checkEmptyFields((self.patHIEntry.toPlainText().strip(),))
        if emailNotEmpty == True and hiNotEmpty == True:
            if checkPatientCommonEntry(data,self.tablePatsDet) and checkHealthInsuranceNumber(self.patHIEntry.toPlainText().strip(),self.tablePatsDet):
                return 4
            else:
                self.showWarningMessage("One or more compulsory fields with wrong data or empty!!")
        elif emailNotEmpty == False and hiNotEmpty == True:
            if checkPatientCommonEntry(data,self.tablePatsDet) and checkHealthInsuranceNumber(self.patHIEntry.toPlainText().strip(),self.tablePatsDet):
                return 3
            else:
                self.showWarningMessage("One or more compulsory fields with wrong data or empty!!")
        elif emailNotEmpty == True and hiNotEmpty == False:
            if checkPatientCommonEntry(data,self.tablePatsDet):
                return 2
            else:
                self.showWarningMessage("One or more compulsory fields with wrong data or empty!!")
        elif emailNotEmpty == False and hiNotEmpty == False:
            if checkPatientCommonEntry(data,self.tablePatsDet):
                return 1
            else:
                self.showWarningMessage("One or more compulsory fields with wrong data or empty!!")

    def addData(self):
        data = (self.patIdEntry.toPlainText().strip(),self.patNameEntry.toPlainText().strip(),
                self.patAgeEntry.toPlainText().strip(),self.patGenderEntry.toPlainText().strip(),
                self.patAddrEntry.toPlainText().strip(),self.patPhoneEntry.toPlainText().strip())
        check = self.verifyData(data)
        if check == 1:
                self.pat_add_updt_thread = AddUpdateDelDeptDataThread(data,1,add_flag=check)
                self.pat_add_updt_thread.start()
                self.pat_add_updt_thread.operationComplete.connect(self.refreshTable)
        elif check == 2:
                data = (self.patIdEntry.toPlainText().strip(),self.patNameEntry.toPlainText().strip(),
                self.patAgeEntry.toPlainText().strip(),self.patGenderEntry.toPlainText().strip(),
                self.patAddrEntry.toPlainText().strip(),self.patPhoneEntry.toPlainText().strip(),
                self.patEmailEntry.toPlainText().strip())
                self.pat_add_updt_thread = AddUpdateDelDeptDataThread(data,1,add_flag=check)
                self.pat_add_updt_thread.start()
                self.pat_add_updt_thread.operationComplete.connect(self.refreshTable)
        elif check == 3:
                data = (self.patIdEntry.toPlainText().strip(),self.patNameEntry.toPlainText().strip(),
                self.patAgeEntry.toPlainText().strip(),self.patGenderEntry.toPlainText().strip(),
                self.patAddrEntry.toPlainText().strip(),self.patPhoneEntry.toPlainText().strip(),
                self.patHIEntry.toPlainText().strip())
                self.pat_add_updt_thread = AddUpdateDelDeptDataThread(data,1,add_flag=check)
                self.pat_add_updt_thread.start()
                self.pat_add_updt_thread.operationComplete.connect(self.refreshTable)
        elif check == 4:
                data = (self.patIdEntry.toPlainText().strip(),self.patNameEntry.toPlainText().strip(),
                self.patAgeEntry.toPlainText().strip(),self.patGenderEntry.toPlainText().strip(),
                self.patAddrEntry.toPlainText().strip(),self.patPhoneEntry.toPlainText().strip(),
                self.patEmailEntry.toPlainText().strip(),self.patHIEntry.toPlainText().strip())
                self.pat_add_updt_thread = AddUpdateDelDeptDataThread(data,1,add_flag=check)
                self.pat_add_updt_thread.start()
                self.pat_add_updt_thread.operationComplete.connect(self.refreshTable)        

    def verifyUpdtData(self,data):
        selected_row = getSelectedRowData(self.tablePatsDet)
        if selected_row is not None:
                emailNotEmpty = checkEmptyFields((self.patEmailEntry.toPlainText().strip(),))
                hiNotEmpty = checkEmptyFields((self.patHIEntry.toPlainText().strip(),))
                if emailNotEmpty == True and hiNotEmpty == True:
                        if checkUpdatePatientCommonEntry(data,self.tablePatsDet) and updtCheckHINo(self.patHIEntry.toPlainText().strip(),self.tablePatsDet):
                                return 4
                        else:
                                self.showWarningMessage("One or more compulsory fields with wrong data or empty!!")
                elif emailNotEmpty == False and hiNotEmpty == True:
                        if checkUpdatePatientCommonEntry(data,self.tablePatsDet) and updtCheckHINo(self.patHIEntry.toPlainText().strip(),self.tablePatsDet):
                                return 3
                        else:
                                self.showWarningMessage("One or more compulsory fields with wrong data or empty!!")
                elif emailNotEmpty == True and hiNotEmpty == False:
                        if checkUpdatePatientCommonEntry(data,self.tablePatsDet):
                                return 2
                        else:
                                self.showWarningMessage("One or more compulsory fields with wrong data or empty!!")
                elif emailNotEmpty == False and hiNotEmpty == False:
                        if checkUpdatePatientCommonEntry(data,self.tablePatsDet):
                                return 1
                        else:
                                self.showWarningMessage("One or more compulsory fields with wrong data or empty!!")
        else:
             self.showWarningMessage("No records selected!!")

    def updtData(self):
        data = (self.patIdEntry.toPlainText().strip(),self.patNameEntry.toPlainText().strip(),
                self.patAgeEntry.toPlainText().strip(),self.patGenderEntry.toPlainText().strip(),
                self.patAddrEntry.toPlainText().strip(),self.patPhoneEntry.toPlainText().strip())
        check = self.verifyUpdtData(data)
        if check==1:
                data = (self.patIdEntry.toPlainText().strip(),self.patNameEntry.toPlainText().strip(),
                self.patAgeEntry.toPlainText().strip(),self.patGenderEntry.toPlainText().strip(),
                self.patAddrEntry.toPlainText().strip(),self.patPhoneEntry.toPlainText().strip(),
                self.patIdEntry.toPlainText().strip())
                self.pat_add_updt_thread = AddUpdateDelDeptDataThread(data,2,add_flag=check)
                self.pat_add_updt_thread.start()
                self.pat_add_updt_thread.operationComplete.connect(self.refreshTable)
        elif check == 2:
                data = (self.patIdEntry.toPlainText().strip(),self.patNameEntry.toPlainText().strip(),
                self.patAgeEntry.toPlainText().strip(),self.patGenderEntry.toPlainText().strip(),
                self.patAddrEntry.toPlainText().strip(),self.patPhoneEntry.toPlainText().strip(),
                self.patEmailEntry.toPlainText().strip(),self.patIdEntry.toPlainText().strip())
                self.pat_add_updt_thread = AddUpdateDelDeptDataThread(data,2,add_flag=check)
                self.pat_add_updt_thread.start()
                self.pat_add_updt_thread.operationComplete.connect(self.refreshTable)
        elif check == 3:
                data = (self.patIdEntry.toPlainText().strip(),self.patNameEntry.toPlainText().strip(),
                self.patAgeEntry.toPlainText().strip(),self.patGenderEntry.toPlainText().strip(),
                self.patAddrEntry.toPlainText().strip(),self.patPhoneEntry.toPlainText().strip(),
                self.patHIEntry.toPlainText().strip(),self.patIdEntry.toPlainText().strip())
                self.pat_add_updt_thread = AddUpdateDelDeptDataThread(data,2,add_flag=check)
                self.pat_add_updt_thread.start()
                self.pat_add_updt_thread.operationComplete.connect(self.refreshTable)
        elif check == 4:
                data = (self.patIdEntry.toPlainText().strip(),self.patNameEntry.toPlainText().strip(),
                self.patAgeEntry.toPlainText().strip(),self.patGenderEntry.toPlainText().strip(),
                self.patAddrEntry.toPlainText().strip(),self.patPhoneEntry.toPlainText().strip(),
                self.patEmailEntry.toPlainText().strip(),self.patHIEntry.toPlainText().strip(),
                self.patIdEntry.toPlainText().strip())
                self.pat_add_updt_thread = AddUpdateDelDeptDataThread(data,2,add_flag=check)
                self.pat_add_updt_thread.start()
                self.pat_add_updt_thread.operationComplete.connect(self.refreshTable) 
        else:
             self.showWarningMessage("Choose correct record!!")


    def delData(self):
        row = getSelectedRowData(self.tablePatsDet)
        if row is not None:
                selected_id_no = row[0]
                self.doc_add_updt_thread = AddUpdateDelDeptDataThread(selected_id_no,3,None)
                self.doc_add_updt_thread.start()
                self.doc_add_updt_thread.operationComplete.connect(self.refreshTable)
        else:
             self.showWarningMessage("Please select record!!")         
    
    def refreshTable(self):
        self.tablePatsDet.clearContents()
        self.tablePatsDet.setRowCount(0)
        self.pat_data_thread = PatDataRetrievalThread()
        self.pat_data_thread.dataRetrieved.connect(self.updatePatTable)
        self.pat_data_thread.start()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 701)
        MainWindow.showMaximized()
        self.admin_activity = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_frame.sizePolicy().hasHeightForWidth())
        self.header_frame.setSizePolicy(sizePolicy)
        self.header_frame.setMinimumSize(QtCore.QSize(1280, 100))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.header_frame.setStyleSheet("background-color:rgb(0, 85, 127);")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_frame = ClickableFrame(self.header_frame)
        self.logo_frame.setMinimumSize(QtCore.QSize(80, 50))
        self.logo_frame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.logo_frame.setStyleSheet("background-color:transparent;\n"
"margin-top:6px;\n"
"margin-bottom:0px;")
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.logo_frame.clicked.connect(self.backHome)
        self.backBtn = QtWidgets.QLabel(self.logo_frame)
        self.backBtn.setGeometry(QtCore.QRect(20, 10, 61, 71))
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backBtn.setStyleSheet("")
        self.backBtn.setText("")
        self.backBtn.setPixmap(QtGui.QPixmap(":/reosurces_logo/back-svgrepo-com.svg"))
        self.backBtn.setScaledContents(True)
        self.backBtn.setAlignment(QtCore.Qt.AlignCenter)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.logo_frame)
        self.title_frame = QtWidgets.QFrame(self.header_frame)
        self.title_frame.setMinimumSize(QtCore.QSize(1280, 0))
        font = QtGui.QFont()
        font.setPointSize(42)
        self.title_frame.setFont(font)
        self.title_frame.setStyleSheet("background-color:transparent;")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.title_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setMinimumSize(QtCore.QSize(800, 0))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color:#fff;")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.title_frame)
        self.verticalLayout_2.addWidget(self.header_frame)
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.activityNameDisp = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.activityNameDisp.setFont(font)
        self.activityNameDisp.setStyleSheet("color:rgb(0, 85, 127);")
        self.activityNameDisp.setObjectName("activityNameDisp")
        self.verticalLayout_22.addWidget(self.activityNameDisp, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("BACKGROUND-COLOR:#c8cbcf;\n"
"BORDER-RADIUS:5PX;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("padding-right:2px;\n"
"padding-left:2px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.patIdEntry = QtWidgets.QTextEdit(self.frame_5)
        self.patIdEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patIdEntry.setFont(font)
        self.patIdEntry.setStyleSheet("background-color:white;")
        self.patIdEntry.setObjectName("patIdEntry")
        self.gridLayout.addWidget(self.patIdEntry, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.patNameEntry = QtWidgets.QTextEdit(self.frame_5)
        self.patNameEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patNameEntry.setFont(font)
        self.patNameEntry.setStyleSheet("background-color:white;")
        self.patNameEntry.setObjectName("patNameEntry")
        self.gridLayout.addWidget(self.patNameEntry, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.patAgeEntry = QtWidgets.QTextEdit(self.frame_5)
        self.patAgeEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patAgeEntry.setFont(font)
        self.patAgeEntry.setStyleSheet("background-color:white;")
        self.patAgeEntry.setObjectName("patAgeEntry")
        self.gridLayout.addWidget(self.patAgeEntry, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.patGenderEntry = QtWidgets.QTextEdit(self.frame_5)
        self.patGenderEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patGenderEntry.setFont(font)
        self.patGenderEntry.setStyleSheet("background-color:white;")
        self.patGenderEntry.setObjectName("patGenderEntry")
        self.gridLayout.addWidget(self.patGenderEntry, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.patAddrEntry = QtWidgets.QTextEdit(self.frame_5)
        self.patAddrEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patAddrEntry.setFont(font)
        self.patAddrEntry.setStyleSheet("background-color:white;")
        self.patAddrEntry.setObjectName("patAddrEntry")
        self.gridLayout.addWidget(self.patAddrEntry, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 2, 1, 1)
        self.patPhoneEntry = QtWidgets.QTextEdit(self.frame_5)
        self.patPhoneEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patPhoneEntry.setFont(font)
        self.patPhoneEntry.setStyleSheet("background-color:white;")
        self.patPhoneEntry.setObjectName("patPhoneEntry")
        self.gridLayout.addWidget(self.patPhoneEntry, 2, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.patEmailEntry = QtWidgets.QTextEdit(self.frame_5)
        self.patEmailEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patEmailEntry.setFont(font)
        self.patEmailEntry.setStyleSheet("background-color:white;")
        self.patEmailEntry.setObjectName("patEmailEntry")
        self.gridLayout.addWidget(self.patEmailEntry, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 2, 1, 1)
        self.patHIEntry = QtWidgets.QTextEdit(self.frame_5)
        self.patHIEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patHIEntry.setFont(font)
        self.patHIEntry.setStyleSheet("background-color:white;")
        self.patHIEntry.setObjectName("patHIEntry")
        self.gridLayout.addWidget(self.patHIEntry, 3, 3, 1, 1)
        self.gridLayout_2.addWidget(self.frame_5, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 0, 1, 1, 2)
        self.addPatBtn = QtWidgets.QPushButton(self.frame)
        self.addPatBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addPatBtn.setFont(font)
        self.addPatBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addPatBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.addPatBtn.setObjectName("addPatBtn")
        self.gridLayout_3.addWidget(self.addPatBtn, 1, 1, 1, 1)
        self.updtPatBtn = QtWidgets.QPushButton(self.frame)
        self.updtPatBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updtPatBtn.setFont(font)
        self.updtPatBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updtPatBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.updtPatBtn.setObjectName("updtPatBtn")
        self.gridLayout_3.addWidget(self.updtPatBtn, 1, 2, 1, 1)
        self.delPatBtn = QtWidgets.QPushButton(self.frame)
        self.delPatBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delPatBtn.setFont(font)
        self.delPatBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delPatBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.delPatBtn.setObjectName("delPatBtn")
        self.gridLayout_3.addWidget(self.delPatBtn, 2, 1, 1, 2)
        self.tablePatsDet = QtWidgets.QTableWidget(self.frame)
        self.tablePatsDet.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tablePatsDet.setFont(font)
        self.tablePatsDet.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tablePatsDet.setStyleSheet("QHeaderView::section {\n"
"                background-color: #00557d;\n"
"                color: white;\n"
"                font-weight: bold;\n"
"padding:5px;\n"
"            }")
        self.tablePatsDet.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tablePatsDet.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tablePatsDet.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablePatsDet.setShowGrid(True)
        self.tablePatsDet.setWordWrap(False)
        self.tablePatsDet.setObjectName("tablePatsDet")
        self.tablePatsDet.setColumnCount(8)
        self.tablePatsDet.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 85, 125))
        self.tablePatsDet.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePatsDet.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePatsDet.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePatsDet.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePatsDet.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePatsDet.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePatsDet.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePatsDet.setHorizontalHeaderItem(7, item)
        self.tablePatsDet.horizontalHeader().setCascadingSectionResizes(True)
        self.tablePatsDet.horizontalHeader().setDefaultSectionSize(180)
        self.tablePatsDet.verticalHeader().setDefaultSectionSize(45)
        self.gridLayout_3.addWidget(self.tablePatsDet, 0, 0, 3, 1)
        self.verticalLayout_2.addWidget(self.frame)

        self.addPatBtn.clicked.connect(self.addData)
        self.updtPatBtn.clicked.connect(self.updtData)
        self.delPatBtn.clicked.connect(self.delData)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "HOSPITAL MANAGEMENT SYSTEM"))
        self.activityNameDisp.setText(_translate("MainWindow", "PATIENT"))
        self.label.setText(_translate("MainWindow", "PATIENT FORM"))
        self.label_2.setText(_translate("MainWindow", "PATIENT ID:"))
        self.label_3.setText(_translate("MainWindow", "NAME :"))
        self.label_4.setText(_translate("MainWindow", "AGE:"))
        self.label_5.setText(_translate("MainWindow", "GENDER:"))
        self.label_7.setText(_translate("MainWindow", "ADDRESS:"))
        self.label_8.setText(_translate("MainWindow", "PHONE:"))
        self.label_9.setText(_translate("MainWindow", "EMAIL:"))
        self.label_10.setText(_translate("MainWindow", "HEALTH INSURANCE:"))
        self.addPatBtn.setText(_translate("MainWindow", "ADD"))
        self.updtPatBtn.setText(_translate("MainWindow", "UPDATE"))
        self.delPatBtn.setText(_translate("MainWindow", "DELETE"))
        self.tablePatsDet.setSortingEnabled(True)
        item = self.tablePatsDet.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PATIENT ID"))
        item = self.tablePatsDet.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.tablePatsDet.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "AGE"))
        item = self.tablePatsDet.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "GENDER"))
        item = self.tablePatsDet.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ADDRESS"))
        item = self.tablePatsDet.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "PHONE"))
        item = self.tablePatsDet.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "EMAIL"))
        item = self.tablePatsDet.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "HEALTH INSURANCE"))
import resources_rc
