# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_emergRoom_lay.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from clickableFrame import ClickableFrame
from database import ConnectionPool,showEmergencyBedAllData,updateEmergencyBedsData
from EntryChecking import checkNumericWith0,checkEmptyFields

class EmerBedDataRetrievalThread(QtCore.QThread):
    dataRetrieved = QtCore.pyqtSignal(object)
    retrievalComplete = QtCore.pyqtSignal()
    def __init__(self, parent=None):
        super(EmerBedDataRetrievalThread, self).__init__(parent)

    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                data = showEmergencyBedAllData(pool)
                self.dataRetrieved.emit(data)
        except Exception as e:
            print(e)

class UpdateBedDataThread(QtCore.QThread):
    operationComplete = QtCore.pyqtSignal()
    def __init__(self,data,parent=None):
        super(UpdateBedDataThread, self).__init__(parent)
        self.data=data
    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                updateEmergencyBedsData(pool,self.data)
                self.operationComplete.emit()

        except Exception as e:
            print(e)

class Admin_emegRoom(object):
    
    def __init__(self):
        self.tableBedsDet = QtWidgets.QTableWidget()
        self.occBedsEntry = QtWidgets.QTextEdit()
        self.vacantBedsEntry = QtWidgets.QTextEdit()
        self.totBedsEntry = QtWidgets.QTextEdit()
        self.beds_data_retrieval_thread = EmerBedDataRetrievalThread()
        self.beds_data_retrieval_thread.dataRetrieved.connect(self.updateBedsTable)
        self.beds_data_retrieval_thread.start()
    
    def backHome(self):
        from Admin_homepage_lay import Admin_home_lay
        self.window = QtWidgets.QMainWindow()
        self.ui = Admin_home_lay()
        self.ui.setupUi(self.window)
        self.window.show()
        self.admin_activity.close()

    def updateBedsTable(self,data):
        self.beds_data_retrieval_thread.retrievalComplete.connect(self.beds_data_retrieval_thread.quit)
        for row_number, row_data in enumerate(data):
            self.tableBedsDet.insertRow(row_number)
            for column_number, column_data in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(column_data))
                self.tableBedsDet.setItem(row_number, column_number, item)
   
    def showWarningMessage(self,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle("Warning")
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def updateData(self):
        data = (self.totBedsEntry.toPlainText().strip(),str(0),self.totBedsEntry.toPlainText().strip())
        if checkNumericWith0(self.totBedsEntry.toPlainText().strip()) and checkEmptyFields(data):
            msg_box = QtWidgets.QMessageBox()
            msg_box.setIcon(QtWidgets.QMessageBox.Warning)
            msg_box.setText("This will clear patient data and update total number of beds.\nProceed?")
            msg_box.setWindowTitle("Warning")
            msg_box.setStandardButtons(QtWidgets.QMessageBox.Ok | QtWidgets.QMessageBox.Cancel)
            result = msg_box.exec_()
            if result == QtWidgets.QMessageBox.Ok:
                self.bed_updt_thread = UpdateBedDataThread(data)
                self.bed_updt_thread.start()
                self.bed_updt_thread.operationComplete.connect(self.refreshTable)
            else:
                pass
        else:
            self.showWarningMessage("Numerical value error!!")
    
    def refreshTable(self):
        self.tableBedsDet.clearContents()
        self.tableBedsDet.setRowCount(0)
        self.beds_data_retrieval_thread = EmerBedDataRetrievalThread()
        self.beds_data_retrieval_thread.dataRetrieved.connect(self.updateBedsTable)
        self.beds_data_retrieval_thread.start()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 701)
        MainWindow.showMaximized()
        self.admin_activity = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_frame.sizePolicy().hasHeightForWidth())
        self.header_frame.setSizePolicy(sizePolicy)
        self.header_frame.setMinimumSize(QtCore.QSize(1280, 100))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.header_frame.setStyleSheet("background-color:rgb(0, 85, 127);")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_frame = ClickableFrame(self.header_frame)
        self.logo_frame.setMinimumSize(QtCore.QSize(80, 50))
        self.logo_frame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.logo_frame.setStyleSheet("background-color:transparent;\n"
"margin-top:6px;\n"
"margin-bottom:0px;")
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.logo_frame.clicked.connect(self.backHome)
        self.backBtn = QtWidgets.QLabel(self.logo_frame)
        self.backBtn.setGeometry(QtCore.QRect(20, 10, 61, 71))
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backBtn.setStyleSheet("")
        self.backBtn.setText("")
        self.backBtn.setPixmap(QtGui.QPixmap(":/reosurces_logo/back-svgrepo-com.svg"))
        self.backBtn.setScaledContents(True)
        self.backBtn.setAlignment(QtCore.Qt.AlignCenter)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.logo_frame)
        self.title_frame = QtWidgets.QFrame(self.header_frame)
        self.title_frame.setMinimumSize(QtCore.QSize(1280, 0))
        font = QtGui.QFont()
        font.setPointSize(42)
        self.title_frame.setFont(font)
        self.title_frame.setStyleSheet("background-color:transparent;")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.title_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setMinimumSize(QtCore.QSize(800, 0))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color:#fff;")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.title_frame)
        self.verticalLayout_2.addWidget(self.header_frame)
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.activityNameDisp = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.activityNameDisp.setFont(font)
        self.activityNameDisp.setStyleSheet("color:rgb(0, 85, 127);")
        self.activityNameDisp.setObjectName("activityNameDisp")
        self.verticalLayout_22.addWidget(self.activityNameDisp, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(15, 9, 15, -1)
        self.gridLayout_2.setHorizontalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("BACKGROUND-COLOR:#c8cbcf;\n"
"BORDER-RADIUS:5PX;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("padding-right:2px;\n"
"padding-left:2px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.totBedsEntry = QtWidgets.QTextEdit(self.frame_5)
        self.totBedsEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totBedsEntry.setFont(font)
        self.totBedsEntry.setStyleSheet("background-color:white;")
        self.totBedsEntry.setObjectName("totBedsEntry")
        self.gridLayout.addWidget(self.totBedsEntry, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.gridLayout_2.addWidget(self.frame_3, 0, 1, 1, 2)
        self.tableBedsDet = QtWidgets.QTableWidget(self.frame)
        self.tableBedsDet.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableBedsDet.setFont(font)
        self.tableBedsDet.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableBedsDet.setStyleSheet("QHeaderView::section {\n"
"                background-color: #00557d;\n"
"                color: white;\n"
"                font-weight: bold;\n"
"padding:5px;\n"
"            }")
        self.tableBedsDet.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableBedsDet.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableBedsDet.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableBedsDet.setShowGrid(True)
        self.tableBedsDet.setWordWrap(False)
        self.tableBedsDet.setObjectName("tableBedsDet")
        self.tableBedsDet.setColumnCount(3)
        self.tableBedsDet.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableBedsDet.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBedsDet.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBedsDet.setHorizontalHeaderItem(2, item)
        self.tableBedsDet.horizontalHeader().setCascadingSectionResizes(True)
        self.tableBedsDet.horizontalHeader().setDefaultSectionSize(300)
        self.tableBedsDet.verticalHeader().setDefaultSectionSize(45)
        self.gridLayout_2.addWidget(self.tableBedsDet, 0, 0, 2, 1, QtCore.Qt.AlignVCenter)
        self.updateTotalBedsBtn = QtWidgets.QPushButton(self.frame)
        self.updateTotalBedsBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateTotalBedsBtn.setFont(font)
        self.updateTotalBedsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updateTotalBedsBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.updateTotalBedsBtn.setObjectName("updateTotalBedsBtn")
        self.gridLayout_2.addWidget(self.updateTotalBedsBtn, 1, 1, 1, 2)
        self.verticalLayout_2.addWidget(self.frame)

        self.updateTotalBedsBtn.clicked.connect(self.updateData)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "HOSPITAL MANAGEMENT SYSTEM"))
        self.activityNameDisp.setText(_translate("MainWindow", "EMERGENCY ROOM TOTAL BEDS"))
        self.label.setText(_translate("MainWindow", "ENTRY FORM"))
        self.label_2.setText(_translate("MainWindow", "TOTAL BEDS AVAILABLE:"))
        self.tableBedsDet.setSortingEnabled(True)
        item = self.tableBedsDet.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "TOTAL BEDS"))
        item = self.tableBedsDet.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "OCCUPIED BEDS"))
        item = self.tableBedsDet.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "VACANT BEDS"))
        self.updateTotalBedsBtn.setText(_translate("MainWindow", "UPDATE"))
import resources_rc
