# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_accountants_lay.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from clickableFrame import ClickableFrame
from database import ConnectionPool,showAllAccountants,addAccountantsData,updtAccountantsData,deleteAccountantsData
from EntryChecking import *

class AccntsDataRetrievalThread(QtCore.QThread):
    dataRetrieved = QtCore.pyqtSignal(object)
    retrievalComplete = QtCore.pyqtSignal()
    def __init__(self, parent=None):
        super(AccntsDataRetrievalThread, self).__init__(parent)

    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                data = showAllAccountants(pool)
                self.dataRetrieved.emit(data)
        except Exception as e:
            print(e)

class AddUpdateDelAccntsDataThread(QtCore.QThread):
    operationComplete = QtCore.pyqtSignal()
    def __init__(self,data,flag,parent=None):
        super(AddUpdateDelAccntsDataThread, self).__init__(parent)
        self.flag=flag
        self.data=data
    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                if(self.flag==1):
                     addAccountantsData(pool,self.data)
                elif(self.flag==2):
                     updtAccountantsData(pool,self.data)
                elif(self.flag==3):
                     deleteAccountantsData(pool,self.data)
                self.operationComplete.emit()

        except Exception as e:
            print(e)


class Admin_accountant(object):
    
    def __init__(self):
        self.tableAccsDet = QtWidgets.QTableWidget()
        self.accIdEntry = QtWidgets.QTextEdit()
        self.accNameEntry = QtWidgets.QTextEdit()
        self.accStatusEntry = QtWidgets.QTextEdit()
        self.accAgeEntry = QtWidgets.QTextEdit()
        self.accGenderEntry = QtWidgets.QTextEdit()
        self.accExpEntry = QtWidgets.QTextEdit()
        self.accFeeEntry = QtWidgets.QTextEdit()
        self.accDeptEntry = QtWidgets.QTextEdit()
        self.accTimeEntry = QtWidgets.QTextEdit()
        self.accDaysEntry = QtWidgets.QTextEdit()
        self.appnt_data_thread = AccntsDataRetrievalThread()
        self.appnt_data_thread.dataRetrieved.connect(self.updateAccntsTable)
        self.appnt_data_thread.start()
    
    def backHome(self):
        from Admin_homepage_lay import Admin_home_lay
        self.window = QtWidgets.QMainWindow()
        self.ui = Admin_home_lay()
        self.ui.setupUi(self.window)
        self.window.show()
        self.admin_activity.close()

    def updateAccntsTable(self,data):
        self.appnt_data_thread.retrievalComplete.connect(self.appnt_data_thread.quit)
        for row_number, row_data in enumerate(data):
            self.tableAccsDet.insertRow(row_number)
            for column_number, column_data in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(column_data))
                self.tableAccsDet.setItem(row_number, column_number, item)

    def showWarningMessage(self,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle("Warning")
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def verifyData(self,data):
        if not checkEmptyFields(data):
                self.showWarningMessage("All Fields are mandatory!!")
        else:
                if not checkAgeOrExpOrFee((self.accAgeEntry.toPlainText().strip(),self.accExpEntry.toPlainText().strip(),
                                        self.accFeeEntry.toPlainText().strip())):
                     self.showWarningMessage("Age/Experince/Fee wrong!!")
                else:
                     if checkLicenseNumber(self.accIdEntry.toPlainText().strip(),self.tableAccsDet):
                        return True
                     else:
                          self.showWarningMessage("Invalid License number!!")
        return False
    
    def addData(self):
        data = (self.accIdEntry.toPlainText().strip(),self.accNameEntry.toPlainText().strip(),
                self.accStatusEntry.toPlainText().strip(),self.accAgeEntry.toPlainText().strip(),
                self.accGenderEntry.toPlainText().strip(),self.accExpEntry.toPlainText().strip(),
                self.accFeeEntry.toPlainText().strip(),self.accDeptEntry.toPlainText().strip(),
                self.accTimeEntry.toPlainText().strip(),self.accDaysEntry.toPlainText().strip())
        if self.verifyData(data):
                self.accnts_add_updt_thread = AddUpdateDelAccntsDataThread(data,flag=1)
                self.accnts_add_updt_thread.start()
                self.accnts_add_updt_thread.operationComplete.connect(self.refreshTable)
        else:
             self.showWarningMessage("Operation failed!!")
    
    def verifyUpdtData(self,data):
        if not checkEmptyFields(data):
                self.showWarningMessage("All Fields are mandatory!!")
        else:
                if not checkAgeOrExpOrFee((self.accAgeEntry.toPlainText().strip(),self.accExpEntry.toPlainText().strip(),
                                        self.accFeeEntry.toPlainText().strip())):
                     self.showWarningMessage("Age/Experince/Fee wrong!!")
                else:
                     try:
                        license_no = int(self.accIdEntry.toPlainText().strip())
                        if int(license_no)>0:
                                row = getSelectedRowData(self.tableAccsDet)
                                if row is not None:
                                        selected_lic_no = row[0]
                                        if str(license_no) != str(selected_lic_no):
                                                row_count = self.tableAccsDet.rowCount()
                                                column_values = []
                                                for row in range(row_count):
                                                        item = self.tableAccsDet.item(row, 0)
                                                        if item is not None:
                                                                column_values.append(item.text())
                                                if str(license_no) not in column_values:
                                                     return True
                                                else:
                                                     self.showWarningMessage("License already in use!!")
                                        else:
                                             return True
                                else:
                                        self.showWarningMessage("Please select record!!")
                                        return True
                        else:
                                self.showWarningMessage("Invalid License number!!")
                     except Exception as e:
                          self.showWarningMessage("Invalid License number!!")   
        return False

    def updtData(self):
        data = (self.accIdEntry.toPlainText().strip(),self.accNameEntry.toPlainText().strip(),
                self.accStatusEntry.toPlainText().strip(),self.accAgeEntry.toPlainText().strip(),
                self.accGenderEntry.toPlainText().strip(),self.accExpEntry.toPlainText().strip(),
                self.accFeeEntry.toPlainText().strip(),self.accDeptEntry.toPlainText().strip(),
                self.accTimeEntry.toPlainText().strip(),self.accDaysEntry.toPlainText().strip(),
                self.accIdEntry.toPlainText().strip())
        if self.verifyUpdtData(data):
                row = getSelectedRowData(self.tableAccsDet)
                if row is not None:
                        self.accnts_add_updt_thread = AddUpdateDelAccntsDataThread(data,flag=2)
                        self.accnts_add_updt_thread.start()
                        self.accnts_add_updt_thread.operationComplete.connect(self.refreshTable)
                else:
                     self.showWarningMessage("Please select record!!")
        else:
             self.showWarningMessage("Operation failed!!")
    
    def delData(self):
        row = getSelectedRowData(self.tableAccsDet)
        if row is not None:
                selected_lic_no = row[0]
                self.accnts_add_updt_thread = AddUpdateDelAccntsDataThread(selected_lic_no,flag=3)
                self.accnts_add_updt_thread.start()
                self.accnts_add_updt_thread.operationComplete.connect(self.refreshTable)
        else:
             self.showWarningMessage("Please select record!!")        
    
    def refreshTable(self):
        self.tableAccsDet.clearContents()
        self.tableAccsDet.setRowCount(0)
        self.doc_data_thread = AccntsDataRetrievalThread()
        self.doc_data_thread.dataRetrieved.connect(self.updateAccntsTable)
        self.doc_data_thread.start()                    

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 701)
        MainWindow.showMaximized()
        self.admin_activity = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_frame.sizePolicy().hasHeightForWidth())
        self.header_frame.setSizePolicy(sizePolicy)
        self.header_frame.setMinimumSize(QtCore.QSize(1280, 100))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.header_frame.setStyleSheet("background-color:rgb(0, 85, 127);")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_frame = ClickableFrame(self.header_frame)
        self.logo_frame.setMinimumSize(QtCore.QSize(80, 50))
        self.logo_frame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.logo_frame.setStyleSheet("background-color:transparent;\n"
"margin-top:6px;\n"
"margin-bottom:0px;")
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.logo_frame.clicked.connect(self.backHome)
        self.backBtn = QtWidgets.QLabel(self.logo_frame)
        self.backBtn.setGeometry(QtCore.QRect(20, 10, 61, 71))
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backBtn.setStyleSheet("")
        self.backBtn.setText("")
        self.backBtn.setPixmap(QtGui.QPixmap(":/reosurces_logo/back-svgrepo-com.svg"))
        self.backBtn.setScaledContents(True)
        self.backBtn.setAlignment(QtCore.Qt.AlignCenter)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.logo_frame)
        self.title_frame = QtWidgets.QFrame(self.header_frame)
        self.title_frame.setMinimumSize(QtCore.QSize(1280, 0))
        font = QtGui.QFont()
        font.setPointSize(42)
        self.title_frame.setFont(font)
        self.title_frame.setStyleSheet("background-color:transparent;")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.title_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setMinimumSize(QtCore.QSize(800, 0))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color:#fff;")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.title_frame)
        self.verticalLayout_2.addWidget(self.header_frame)
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.activityNameDisp = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.activityNameDisp.setFont(font)
        self.activityNameDisp.setStyleSheet("color:rgb(0, 85, 127);")
        self.activityNameDisp.setObjectName("activityNameDisp")
        self.verticalLayout_22.addWidget(self.activityNameDisp, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(15, 9, 15, -1)
        self.gridLayout_2.setHorizontalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("BACKGROUND-COLOR:#c8cbcf;\n"
"BORDER-RADIUS:5PX;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("padding-right:2px;\n"
"padding-left:2px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setHorizontalSpacing(25)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.accExpEntry = QtWidgets.QTextEdit(self.frame_5)
        self.accExpEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accExpEntry.setFont(font)
        self.accExpEntry.setStyleSheet("background-color:white;")
        self.accExpEntry.setObjectName("accExpEntry")
        self.gridLayout.addWidget(self.accExpEntry, 3, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.accGenderEntry = QtWidgets.QTextEdit(self.frame_5)
        self.accGenderEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accGenderEntry.setFont(font)
        self.accGenderEntry.setStyleSheet("background-color:white;")
        self.accGenderEntry.setObjectName("accGenderEntry")
        self.gridLayout.addWidget(self.accGenderEntry, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.accNameEntry = QtWidgets.QTextEdit(self.frame_5)
        self.accNameEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accNameEntry.setFont(font)
        self.accNameEntry.setStyleSheet("background-color:white;")
        self.accNameEntry.setObjectName("accNameEntry")
        self.gridLayout.addWidget(self.accNameEntry, 0, 3, 1, 1)
        self.accAgeEntry = QtWidgets.QTextEdit(self.frame_5)
        self.accAgeEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accAgeEntry.setFont(font)
        self.accAgeEntry.setStyleSheet("background-color:white;")
        self.accAgeEntry.setObjectName("accAgeEntry")
        self.gridLayout.addWidget(self.accAgeEntry, 2, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.accStatusEntry = QtWidgets.QTextEdit(self.frame_5)
        self.accStatusEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accStatusEntry.setFont(font)
        self.accStatusEntry.setStyleSheet("background-color:white;")
        self.accStatusEntry.setObjectName("accStatusEntry")
        self.gridLayout.addWidget(self.accStatusEntry, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 2, 1, 1)
        self.accDaysEntry = QtWidgets.QTextEdit(self.frame_5)
        self.accDaysEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accDaysEntry.setFont(font)
        self.accDaysEntry.setStyleSheet("background-color:white;")
        self.accDaysEntry.setObjectName("accDaysEntry")
        self.gridLayout.addWidget(self.accDaysEntry, 7, 3, 1, 1)
        self.accDeptEntry = QtWidgets.QTextEdit(self.frame_5)
        self.accDeptEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accDeptEntry.setFont(font)
        self.accDeptEntry.setStyleSheet("background-color:white;")
        self.accDeptEntry.setObjectName("accDeptEntry")
        self.gridLayout.addWidget(self.accDeptEntry, 4, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 7, 2, 1, 1)
        self.accIdEntry = QtWidgets.QTextEdit(self.frame_5)
        self.accIdEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accIdEntry.setFont(font)
        self.accIdEntry.setStyleSheet("background-color:white;")
        self.accIdEntry.setObjectName("accIdEntry")
        self.gridLayout.addWidget(self.accIdEntry, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.accFeeEntry = QtWidgets.QTextEdit(self.frame_5)
        self.accFeeEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accFeeEntry.setFont(font)
        self.accFeeEntry.setStyleSheet("background-color:white;")
        self.accFeeEntry.setObjectName("accFeeEntry")
        self.gridLayout.addWidget(self.accFeeEntry, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 7, 0, 1, 1)
        self.accTimeEntry = QtWidgets.QTextEdit(self.frame_5)
        self.accTimeEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accTimeEntry.setFont(font)
        self.accTimeEntry.setStyleSheet("background-color:white;")
        self.accTimeEntry.setObjectName("accTimeEntry")
        self.gridLayout.addWidget(self.accTimeEntry, 7, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.gridLayout_2.addWidget(self.frame_3, 0, 1, 1, 2)
        self.delAccBtn = QtWidgets.QPushButton(self.frame)
        self.delAccBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delAccBtn.setFont(font)
        self.delAccBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delAccBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.delAccBtn.setObjectName("delAccBtn")
        self.gridLayout_2.addWidget(self.delAccBtn, 2, 1, 1, 2)
        self.addAccBtn = QtWidgets.QPushButton(self.frame)
        self.addAccBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addAccBtn.setFont(font)
        self.addAccBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addAccBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.addAccBtn.setObjectName("addAccBtn")
        self.gridLayout_2.addWidget(self.addAccBtn, 1, 1, 1, 1)
        self.tableAccsDet = QtWidgets.QTableWidget(self.frame)
        self.tableAccsDet.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableAccsDet.setFont(font)
        self.tableAccsDet.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableAccsDet.setStyleSheet("QHeaderView::section {\n"
"                background-color: #00557d;\n"
"                color: white;\n"
"                font-weight: bold;\n"
"padding:5px;\n"
"            }")
        self.tableAccsDet.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableAccsDet.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableAccsDet.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableAccsDet.setShowGrid(True)
        self.tableAccsDet.setWordWrap(False)
        self.tableAccsDet.setObjectName("tableAccsDet")
        self.tableAccsDet.setColumnCount(10)
        self.tableAccsDet.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 85, 125))
        self.tableAccsDet.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccsDet.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccsDet.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccsDet.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccsDet.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccsDet.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccsDet.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccsDet.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccsDet.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccsDet.setHorizontalHeaderItem(9, item)
        self.tableAccsDet.horizontalHeader().setCascadingSectionResizes(True)
        self.tableAccsDet.horizontalHeader().setDefaultSectionSize(180)
        self.tableAccsDet.verticalHeader().setDefaultSectionSize(45)
        self.gridLayout_2.addWidget(self.tableAccsDet, 0, 0, 3, 1)
        self.updtAccBtn = QtWidgets.QPushButton(self.frame)
        self.updtAccBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updtAccBtn.setFont(font)
        self.updtAccBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updtAccBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.updtAccBtn.setObjectName("updtAccBtn")
        self.gridLayout_2.addWidget(self.updtAccBtn, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)

        self.addAccBtn.clicked.connect(self.addData)
        self.updtAccBtn.clicked.connect(self.updtData)
        self.delAccBtn.clicked.connect(self.delData)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "HOSPITAL MANAGEMENT SYSTEM"))
        self.activityNameDisp.setText(_translate("MainWindow", "ACCOUNTANTS"))
        self.label.setText(_translate("MainWindow", "ACCOUNTANT FORM"))
        self.label_5.setText(_translate("MainWindow", "AGE:"))
        self.label_8.setText(_translate("MainWindow", "EXPERIENCE:"))
        self.label_4.setText(_translate("MainWindow", "STATUS:"))
        self.label_3.setText(_translate("MainWindow", "NAME :"))
        self.label_2.setText(_translate("MainWindow", "ACCOUNTANT ID:"))
        self.label_10.setText(_translate("MainWindow", "DEPARTMENT:"))
        self.label_7.setText(_translate("MainWindow", "GENDER:"))
        self.label_12.setText(_translate("MainWindow", "APPNT DAYS:"))
        self.label_11.setText(_translate("MainWindow", "FEE:"))
        self.label_13.setText(_translate("MainWindow", "TIME SLOT:"))
        self.delAccBtn.setText(_translate("MainWindow", "DELETE"))
        self.addAccBtn.setText(_translate("MainWindow", "ADD"))
        self.tableAccsDet.setSortingEnabled(True)
        item = self.tableAccsDet.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ACCOUNTANT ID"))
        item = self.tableAccsDet.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.tableAccsDet.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "STATUS"))
        item = self.tableAccsDet.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "AGE"))
        item = self.tableAccsDet.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "GENDER"))
        item = self.tableAccsDet.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "EXP"))
        item = self.tableAccsDet.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "FEE"))
        item = self.tableAccsDet.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "DEPT"))
        item = self.tableAccsDet.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "TIME SLOT"))
        item = self.tableAccsDet.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "APPNT DAYS"))
        self.updtAccBtn.setText(_translate("MainWindow", "UPDATE"))
import resources_rc
