# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_pharmacists_lay.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from clickableFrame import ClickableFrame
from EntryChecking import *
from database import ConnectionPool,showAllPharmacists,addPharmacistsData,updtPharmacistsData,deletePharmacistsData

class PharmacistDataRetrievalThread(QtCore.QThread):
    dataRetrieved = QtCore.pyqtSignal(object)
    retrievalComplete = QtCore.pyqtSignal()
    def __init__(self, parent=None):
        super(PharmacistDataRetrievalThread, self).__init__(parent)

    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                data = showAllPharmacists(pool)
                self.dataRetrieved.emit(data)
        except Exception as e:
            print(e)

class AddUpdateDelPharmacistDataThread(QtCore.QThread):
    operationComplete = QtCore.pyqtSignal()
    def __init__(self,data,flag,parent=None):
        super(AddUpdateDelPharmacistDataThread, self).__init__(parent)
        self.flag=flag
        self.data=data
    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                if(self.flag==1):
                     addPharmacistsData(pool,self.data)
                elif(self.flag==2):
                     updtPharmacistsData(pool,self.data)
                elif(self.flag==3):
                     deletePharmacistsData(pool,self.data)
                self.operationComplete.emit()

        except Exception as e:
            print(e)

class Admin_pharmacists(object):
    
    def __init__(self):
        self.tablePharmsDet = QtWidgets.QTableWidget()
        self.licNoEntry = QtWidgets.QTextEdit()
        self.pharmNameEntry = QtWidgets.QTextEdit()
        self.pharmStatusEntry = QtWidgets.QTextEdit()
        self.pharmAgeEntry = QtWidgets.QTextEdit()
        self.pharmGenEntry = QtWidgets.QTextEdit()
        self.pharmExpEntry = QtWidgets.QTextEdit()
        self.pharmSpecEntry = QtWidgets.QTextEdit() 
        self.phramDeptEntry = QtWidgets.QTextEdit()
        self.phramFeeEntry = QtWidgets.QTextEdit()
        self.pharmAppntEntry = QtWidgets.QTextEdit()
        self.phramTimeEntry = QtWidgets.QTextEdit()
        self.pharma_data_thread = PharmacistDataRetrievalThread()
        self.pharma_data_thread.dataRetrieved.connect(self.updatePharmaTable)
        self.pharma_data_thread.start()
    
    def backHome(self):
        from Admin_homepage_lay import Admin_home_lay
        self.window = QtWidgets.QMainWindow()
        self.ui = Admin_home_lay()
        self.ui.setupUi(self.window)
        self.window.show()
        self.admin_activity.close()

    def updatePharmaTable(self,data):
        self.pharma_data_thread.retrievalComplete.connect(self.pharma_data_thread.quit)
        for row_number, row_data in enumerate(data):
            self.tablePharmsDet.insertRow(row_number)
            for column_number, column_data in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(column_data))
                self.tablePharmsDet.setItem(row_number, column_number, item)
    
    def showWarningMessage(self,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle("Warning")
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def verifyData(self,data):
        if not checkEmptyFields(data):
                self.showWarningMessage("All Fields are mandatory!!")
        else:
                if not checkAgeOrExpOrFee((self.pharmAgeEntry.toPlainText().strip(),self.pharmExpEntry.toPlainText().strip(),
                                        self.phramFeeEntry.toPlainText().strip())):
                     self.showWarningMessage("Age/Experince/Fee wrong!!")
                else:
                     if checkLicenseNumber(self.licNoEntry.toPlainText().strip(),self.tablePharmsDet):
                        return True
                     else:
                          self.showWarningMessage("Invalid License number!!")
        return False

    def addData(self):
        data = (self.licNoEntry.toPlainText().strip(),self.pharmNameEntry.toPlainText().strip(),
                self.pharmStatusEntry.toPlainText().strip(),self.pharmAgeEntry.toPlainText().strip(),
                self.pharmGenEntry.toPlainText().strip(),self.pharmExpEntry.toPlainText().strip(),
                self.pharmSpecEntry.toPlainText().strip(),self.phramDeptEntry.toPlainText().strip(),
                self.phramFeeEntry.toPlainText().strip(),self.pharmAppntEntry.toPlainText().strip(),
                self.phramTimeEntry.toPlainText().strip())
        if self.verifyData(data):
                self.pharmacist_add_updt_thread = AddUpdateDelPharmacistDataThread(data,flag=1)
                self.pharmacist_add_updt_thread.start()
                self.pharmacist_add_updt_thread.operationComplete.connect(self.refreshTable)
    
    def verifyUpdtData(self,data):
        if not checkEmptyFields(data):
                self.showWarningMessage("All Fields are mandatory!!")
        else:
                if not checkAgeOrExpOrFee((self.pharmAgeEntry.toPlainText().strip(),self.pharmExpEntry.toPlainText().strip(),
                                        self.phramFeeEntry.toPlainText().strip())):
                     self.showWarningMessage("Age/Experince/Fee wrong!!")
                else:
                     try:
                        license_no = int(self.licNoEntry.toPlainText().strip())
                        if int(license_no)>0:
                                row = getSelectedRowData(self.tablePharmsDet)
                                if row is not None:
                                        selected_lic_no = row[0]
                                        if str(license_no) != str(selected_lic_no):
                                                row_count = self.tablePharmsDet.rowCount()
                                                column_values = []
                                                for row in range(row_count):
                                                        item = self.tablePharmsDet.item(row, 0)
                                                        if item is not None:
                                                                column_values.append(item.text())
                                                if str(license_no) not in column_values:
                                                     return True
                                                else:
                                                     self.showWarningMessage("License already in use!!")
                                        else:
                                             return True
                                else:
                                        self.showWarningMessage("Please select record!!")
                                        return True
                        else:
                                self.showWarningMessage("Invalid License number!!")
                     except Exception as e:
                          self.showWarningMessage("Invalid License number!!")   
        return False

    def updtData(self):
        data = (self.licNoEntry.toPlainText().strip(),self.pharmNameEntry.toPlainText().strip(),
                self.pharmStatusEntry.toPlainText().strip(),self.pharmAgeEntry.toPlainText().strip(),
                self.pharmGenEntry.toPlainText().strip(),self.pharmExpEntry.toPlainText().strip(),
                self.pharmSpecEntry.toPlainText().strip(),self.phramDeptEntry.toPlainText().strip(),
                self.phramFeeEntry.toPlainText().strip(),self.pharmAppntEntry.toPlainText().strip(),
                self.phramTimeEntry.toPlainText().strip(),self.licNoEntry.toPlainText().strip())
        if self.verifyUpdtData(data):
                self.pharmacist_add_updt_thread = AddUpdateDelPharmacistDataThread(data,flag=2)
                self.pharmacist_add_updt_thread.start()
                self.pharmacist_add_updt_thread.operationComplete.connect(self.refreshTable)
    
    def deleteData(self):
        row = getSelectedRowData(self.tablePharmsDet)
        if row is not None:
                selected_lic_no = row[0]
                self.pharmacist_add_updt_thread = AddUpdateDelPharmacistDataThread(selected_lic_no,flag=3)
                self.pharmacist_add_updt_thread.start()
                self.pharmacist_add_updt_thread.operationComplete.connect(self.refreshTable)
        else:
             self.showWarningMessage("Please select record!!")    
    
    def refreshTable(self):
        self.tablePharmsDet.clearContents()
        self.tablePharmsDet.setRowCount(0)
        self.pharma_data_thread = PharmacistDataRetrievalThread()
        self.pharma_data_thread.dataRetrieved.connect(self.updatePharmaTable)
        self.pharma_data_thread.start()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 701)
        MainWindow.showMaximized()
        self.admin_activity = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_frame.sizePolicy().hasHeightForWidth())
        self.header_frame.setSizePolicy(sizePolicy)
        self.header_frame.setMinimumSize(QtCore.QSize(1280, 100))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.header_frame.setStyleSheet("background-color:rgb(0, 85, 127);")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_frame = ClickableFrame(self.header_frame)
        self.logo_frame.setMinimumSize(QtCore.QSize(80, 50))
        self.logo_frame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.logo_frame.setStyleSheet("background-color:transparent;\n"
"margin-top:6px;\n"
"margin-bottom:0px;")
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.logo_frame.clicked.connect(self.backHome)
        self.backBtn = QtWidgets.QLabel(self.logo_frame)
        self.backBtn.setGeometry(QtCore.QRect(20, 10, 61, 71))
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backBtn.setStyleSheet("")
        self.backBtn.setText("")
        self.backBtn.setPixmap(QtGui.QPixmap(":/reosurces_logo/back-svgrepo-com.svg"))
        self.backBtn.setScaledContents(True)
        self.backBtn.setAlignment(QtCore.Qt.AlignCenter)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.logo_frame)
        self.title_frame = QtWidgets.QFrame(self.header_frame)
        self.title_frame.setMinimumSize(QtCore.QSize(1280, 0))
        font = QtGui.QFont()
        font.setPointSize(42)
        self.title_frame.setFont(font)
        self.title_frame.setStyleSheet("background-color:transparent;")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.title_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setMinimumSize(QtCore.QSize(800, 0))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color:#fff;")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.title_frame)
        self.verticalLayout_2.addWidget(self.header_frame)
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.activityNameDisp = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.activityNameDisp.setFont(font)
        self.activityNameDisp.setStyleSheet("color:rgb(0, 85, 127);")
        self.activityNameDisp.setObjectName("activityNameDisp")
        self.verticalLayout_22.addWidget(self.activityNameDisp, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(15, 9, 15, -1)
        self.gridLayout_2.setHorizontalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("BACKGROUND-COLOR:#c8cbcf;\n"
"BORDER-RADIUS:5PX;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("padding-right:2px;\n"
"padding-left:2px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setHorizontalSpacing(25)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.pharmExpEntry = QtWidgets.QTextEdit(self.frame_5)
        self.pharmExpEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pharmExpEntry.setFont(font)
        self.pharmExpEntry.setStyleSheet("background-color:white;")
        self.pharmExpEntry.setObjectName("pharmExpEntry")
        self.gridLayout.addWidget(self.pharmExpEntry, 3, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.pharmGenEntry = QtWidgets.QTextEdit(self.frame_5)
        self.pharmGenEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pharmGenEntry.setFont(font)
        self.pharmGenEntry.setStyleSheet("background-color:white;")
        self.pharmGenEntry.setObjectName("pharmGenEntry")
        self.gridLayout.addWidget(self.pharmGenEntry, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.pharmNameEntry = QtWidgets.QTextEdit(self.frame_5)
        self.pharmNameEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pharmNameEntry.setFont(font)
        self.pharmNameEntry.setStyleSheet("background-color:white;")
        self.pharmNameEntry.setObjectName("pharmNameEntry")
        self.gridLayout.addWidget(self.pharmNameEntry, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.pharmAgeEntry = QtWidgets.QTextEdit(self.frame_5)
        self.pharmAgeEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pharmAgeEntry.setFont(font)
        self.pharmAgeEntry.setStyleSheet("background-color:white;")
        self.pharmAgeEntry.setObjectName("pharmAgeEntry")
        self.gridLayout.addWidget(self.pharmAgeEntry, 2, 3, 1, 1)
        self.pharmSpecEntry = QtWidgets.QTextEdit(self.frame_5)
        self.pharmSpecEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pharmSpecEntry.setFont(font)
        self.pharmSpecEntry.setStyleSheet("background-color:white;")
        self.pharmSpecEntry.setObjectName("pharmSpecEntry")
        self.gridLayout.addWidget(self.pharmSpecEntry, 4, 1, 1, 1)
        self.phramFeeEntry = QtWidgets.QTextEdit(self.frame_5)
        self.phramFeeEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.phramFeeEntry.setFont(font)
        self.phramFeeEntry.setStyleSheet("background-color:white;")
        self.phramFeeEntry.setObjectName("phramFeeEntry")
        self.gridLayout.addWidget(self.phramFeeEntry, 7, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 0, 1, 1)
        self.pharmStatusEntry = QtWidgets.QTextEdit(self.frame_5)
        self.pharmStatusEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pharmStatusEntry.setFont(font)
        self.pharmStatusEntry.setStyleSheet("background-color:white;")
        self.pharmStatusEntry.setObjectName("pharmStatusEntry")
        self.gridLayout.addWidget(self.pharmStatusEntry, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 2, 1, 1)
        self.pharmAppntEntry = QtWidgets.QTextEdit(self.frame_5)
        self.pharmAppntEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pharmAppntEntry.setFont(font)
        self.pharmAppntEntry.setStyleSheet("background-color:white;")
        self.pharmAppntEntry.setObjectName("pharmAppntEntry")
        self.gridLayout.addWidget(self.pharmAppntEntry, 7, 3, 1, 1)
        self.phramDeptEntry = QtWidgets.QTextEdit(self.frame_5)
        self.phramDeptEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.phramDeptEntry.setFont(font)
        self.phramDeptEntry.setStyleSheet("background-color:white;")
        self.phramDeptEntry.setObjectName("phramDeptEntry")
        self.gridLayout.addWidget(self.phramDeptEntry, 4, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 7, 2, 1, 1)
        self.licNoEntry = QtWidgets.QTextEdit(self.frame_5)
        self.licNoEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.licNoEntry.setFont(font)
        self.licNoEntry.setStyleSheet("background-color:white;")
        self.licNoEntry.setObjectName("licNoEntry")
        self.gridLayout.addWidget(self.licNoEntry, 0, 1, 1, 1)
        self.phramTimeEntry = QtWidgets.QTextEdit(self.frame_5)
        self.phramTimeEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.phramTimeEntry.setFont(font)
        self.phramTimeEntry.setStyleSheet("background-color:white;")
        self.phramTimeEntry.setObjectName("phramTimeEntry")
        self.gridLayout.addWidget(self.phramTimeEntry, 8, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 8, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.gridLayout_2.addWidget(self.frame_3, 0, 1, 1, 2)
        self.delPharmBtn = QtWidgets.QPushButton(self.frame)
        self.delPharmBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delPharmBtn.setFont(font)
        self.delPharmBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delPharmBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.delPharmBtn.setObjectName("delPharmBtn")
        self.gridLayout_2.addWidget(self.delPharmBtn, 2, 1, 1, 2)
        self.addPharmBtn = QtWidgets.QPushButton(self.frame)
        self.addPharmBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addPharmBtn.setFont(font)
        self.addPharmBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addPharmBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.addPharmBtn.setObjectName("addPharmBtn")
        self.gridLayout_2.addWidget(self.addPharmBtn, 1, 1, 1, 1)
        self.tablePharmsDet = QtWidgets.QTableWidget(self.frame)
        self.tablePharmsDet.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tablePharmsDet.setFont(font)
        self.tablePharmsDet.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tablePharmsDet.setStyleSheet("QHeaderView::section {\n"
"                background-color: #00557d;\n"
"                color: white;\n"
"                font-weight: bold;\n"
"padding:5px;\n"
"            }")
        self.tablePharmsDet.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tablePharmsDet.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tablePharmsDet.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablePharmsDet.setShowGrid(True)
        self.tablePharmsDet.setWordWrap(False)
        self.tablePharmsDet.setObjectName("tablePharmsDet")
        self.tablePharmsDet.setColumnCount(11)
        self.tablePharmsDet.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 85, 125))
        self.tablePharmsDet.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePharmsDet.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePharmsDet.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePharmsDet.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePharmsDet.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePharmsDet.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePharmsDet.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePharmsDet.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePharmsDet.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePharmsDet.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePharmsDet.setHorizontalHeaderItem(10, item)
        self.tablePharmsDet.horizontalHeader().setCascadingSectionResizes(True)
        self.tablePharmsDet.horizontalHeader().setDefaultSectionSize(180)
        self.tablePharmsDet.verticalHeader().setDefaultSectionSize(45)
        self.gridLayout_2.addWidget(self.tablePharmsDet, 0, 0, 3, 1)
        self.updtPharmBtn = QtWidgets.QPushButton(self.frame)
        self.updtPharmBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updtPharmBtn.setFont(font)
        self.updtPharmBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updtPharmBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.updtPharmBtn.setObjectName("updtPharmBtn")
        self.gridLayout_2.addWidget(self.updtPharmBtn, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)

        self.addPharmBtn.clicked.connect(self.addData)
        self.updtPharmBtn.clicked.connect(self.updtData)
        self.delPharmBtn.clicked.connect(self.deleteData)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "HOSPITAL MANAGEMENT SYSTEM"))
        self.activityNameDisp.setText(_translate("MainWindow", "PHARMACISTS"))
        self.label.setText(_translate("MainWindow", "PHARMACIST FORM"))
        self.label_5.setText(_translate("MainWindow", "AGE:"))
        self.label_8.setText(_translate("MainWindow", "EXPERIENCE:"))
        self.label_4.setText(_translate("MainWindow", "STATUS:"))
        self.label_9.setText(_translate("MainWindow", "SPECIALITY:"))
        self.label_3.setText(_translate("MainWindow", "NAME :"))
        self.label_2.setText(_translate("MainWindow", "LICENSE NO :"))
        self.label_11.setText(_translate("MainWindow", "FEE:"))
        self.label_10.setText(_translate("MainWindow", "DEPARTMENT:"))
        self.label_7.setText(_translate("MainWindow", "GENDER:"))
        self.label_12.setText(_translate("MainWindow", "APPNT DAYS:"))
        self.label_13.setText(_translate("MainWindow", "TIME SLOT:"))
        self.delPharmBtn.setText(_translate("MainWindow", "DELETE"))
        self.addPharmBtn.setText(_translate("MainWindow", "ADD"))
        self.tablePharmsDet.setSortingEnabled(True)
        item = self.tablePharmsDet.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "LICENSE NO"))
        item = self.tablePharmsDet.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.tablePharmsDet.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "STATUS"))
        item = self.tablePharmsDet.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "AGE"))
        item = self.tablePharmsDet.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "GENDER"))
        item = self.tablePharmsDet.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "EXP"))
        item = self.tablePharmsDet.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "SPECIALITY"))
        item = self.tablePharmsDet.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "DEPT"))
        item = self.tablePharmsDet.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "FEE"))
        item = self.tablePharmsDet.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "APPNT DAYS"))
        item = self.tablePharmsDet.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "TIME SLOT"))
        self.updtPharmBtn.setText(_translate("MainWindow", "UPDATE"))
import resources_rc
