# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_doctors_lay.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from clickableFrame import ClickableFrame
from utils import getSelectedRowData
from database import ConnectionPool,showDoctorsData,addDocData,updteDocData,deleteDocData
from EntryChecking import *

class DocDataRetrievalThread(QtCore.QThread):
    dataRetrieved = QtCore.pyqtSignal(object)
    retrievalComplete = QtCore.pyqtSignal()
    def __init__(self, parent=None):
        super(DocDataRetrievalThread, self).__init__(parent)

    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                data = showDoctorsData(pool)
                self.dataRetrieved.emit(data)
        except Exception as e:
            print(e)

class AddUpdateDelDocDataThread(QtCore.QThread):
    operationComplete = QtCore.pyqtSignal()
    def __init__(self,data,flag,parent=None):
        super(AddUpdateDelDocDataThread, self).__init__(parent)
        self.flag=flag
        self.data=data
    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                if(self.flag==1):
                     addDocData(pool,self.data)
                elif(self.flag==2):
                     updteDocData(pool,self.data)
                elif(self.flag==3):
                     deleteDocData(pool,self.data)
                self.operationComplete.emit()

        except Exception as e:
            print(e)

class Admin_doctors(object):
    
    def __init__(self):
        self.licenseNoEntry = QtWidgets.QTextEdit()
        self.docNameEntry = QtWidgets.QTextEdit()
        self.docStatusEntry = QtWidgets.QTextEdit()
        self.docAgeEntry = QtWidgets.QTextEdit()
        self.docGenEntry = QtWidgets.QTextEdit()
        self.docExpEntry = QtWidgets.QTextEdit()
        self.docSpecialityEntry = QtWidgets.QTextEdit()
        self.docDeptEntry = QtWidgets.QTextEdit()
        self.docFeeEntry = QtWidgets.QTextEdit()
        self.doc_appntsEntry = QtWidgets.QTextEdit()
        self.docTimeSlotEntry = QtWidgets.QTextEdit()
        self.doc_data_thread = DocDataRetrievalThread()
        self.doc_data_thread.dataRetrieved.connect(self.updateDocTable)
        self.doc_data_thread.start()

    def backHome(self):
        from Admin_homepage_lay import Admin_home_lay
        self.window = QtWidgets.QMainWindow()
        self.ui = Admin_home_lay()
        self.ui.setupUi(self.window)
        self.window.show()
        self.admin_activity.close()

    def updateDocTable(self,data):
        self.doc_data_thread.retrievalComplete.connect(self.doc_data_thread.quit)
        for row_number, row_data in enumerate(data):
            self.tableDocsDet.insertRow(row_number)
            for column_number, column_data in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(column_data))
                self.tableDocsDet.setItem(row_number, column_number, item)

    def showWarningMessage(self,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle("Warning")
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def verifyData(self,data):
        if not checkEmptyFields(data):
                self.showWarningMessage("All Fields are mandatory!!")
        else:
                if not checkAgeOrExpOrFee((self.docAgeEntry.toPlainText().strip(),self.docExpEntry.toPlainText().strip(),
                                        self.docFeeEntry.toPlainText().strip())):
                     self.showWarningMessage("Age/Experince/Fee wrong!!")
                else:
                     if checkLicenseNumber(self.licenseNoEntry.toPlainText().strip(),self.tableDocsDet):
                        return True
                     else:
                          self.showWarningMessage("Invalid License number!!")
        return False
    
    def addData(self):
        data = (self.licenseNoEntry.toPlainText().strip(),self.docNameEntry.toPlainText().strip(),
                self.docStatusEntry.toPlainText().strip(),self.docAgeEntry.toPlainText().strip(),
                self.docGenEntry.toPlainText().strip(),self.docExpEntry.toPlainText().strip(),
                self.docSpecialityEntry.toPlainText().strip(),self.docDeptEntry.toPlainText().strip(),
                self.docFeeEntry.toPlainText().strip(),self.doc_appntsEntry.toPlainText().strip(),
                self.docTimeSlotEntry.toPlainText().strip())
        if self.verifyData(data):
                self.doc_add_updt_thread = AddUpdateDelDocDataThread(data,flag=1)
                self.doc_add_updt_thread.start()
                self.doc_add_updt_thread.operationComplete.connect(self.refreshTable)
        else:
             self.showWarningMessage("Operation failed!!")
    
    def verifyUpdtData(self,data):
        if not checkEmptyFields(data):
                self.showWarningMessage("All Fields are mandatory!!")
        else:
                if not checkAgeOrExpOrFee((self.docAgeEntry.toPlainText().strip(),self.docExpEntry.toPlainText().strip(),
                                        self.docFeeEntry.toPlainText().strip())):
                     self.showWarningMessage("Age/Experince/Fee wrong!!")
                else:
                     try:
                        license_no = int(self.licenseNoEntry.toPlainText().strip())
                        if int(license_no)>0:
                                row = getSelectedRowData(self.tableDocsDet)
                                if row is not None:
                                        selected_lic_no = row[0]
                                        if str(license_no) != str(selected_lic_no):
                                                row_count = self.tableDocsDet.rowCount()
                                                column_values = []
                                                for row in range(row_count):
                                                        item = self.tableDocsDet.item(row, 0)
                                                        if item is not None:
                                                                column_values.append(item.text())
                                                if str(license_no) not in column_values:
                                                     return True
                                                else:
                                                     self.showWarningMessage("License already in use!!")
                                        else:
                                             return True
                                else:
                                        self.showWarningMessage("Please select record!!")
                                        return True
                        else:
                                self.showWarningMessage("Invalid License number!!")
                     except Exception as e:
                          self.showWarningMessage("Invalid License number!!")   
        return False

    def updtData(self):
        data = (self.licenseNoEntry.toPlainText().strip(),self.docNameEntry.toPlainText().strip(),
                self.docStatusEntry.toPlainText().strip(),self.docAgeEntry.toPlainText().strip(),
                self.docGenEntry.toPlainText().strip(),self.docExpEntry.toPlainText().strip(),
                self.docSpecialityEntry.toPlainText().strip(),self.docDeptEntry.toPlainText().strip(),
                self.docFeeEntry.toPlainText().strip(),self.doc_appntsEntry.toPlainText().strip(),
                self.docTimeSlotEntry.toPlainText().strip())
        if self.verifyUpdtData(data):
                row = getSelectedRowData(self.tableDocsDet)
                if row is not None:
                        selected_lic_no = row[0]
                        data = (self.licenseNoEntry.toPlainText().strip(),self.docNameEntry.toPlainText().strip(),
                        self.docStatusEntry.toPlainText().strip(),self.docAgeEntry.toPlainText().strip(),
                        self.docGenEntry.toPlainText().strip(),self.docExpEntry.toPlainText().strip(),
                        self.docSpecialityEntry.toPlainText().strip(),self.docDeptEntry.toPlainText().strip(),
                        self.docFeeEntry.toPlainText().strip(),self.doc_appntsEntry.toPlainText().strip(),
                        self.docTimeSlotEntry.toPlainText().strip(),selected_lic_no)
                        self.doc_add_updt_thread = AddUpdateDelDocDataThread(data,flag=2)
                        self.doc_add_updt_thread.start()
                        self.doc_add_updt_thread.operationComplete.connect(self.refreshTable)
                else:
                     self.showWarningMessage("Please select record!!")
        else:
             self.showWarningMessage("Operation failed!!")
    
    def delData(self):
        row = getSelectedRowData(self.tableDocsDet)
        if row is not None:
                selected_lic_no = row[0]
                self.doc_add_updt_thread = AddUpdateDelDocDataThread(selected_lic_no,flag=3)
                self.doc_add_updt_thread.start()
                self.doc_add_updt_thread.operationComplete.connect(self.refreshTable)
        else:
             self.showWarningMessage("Please select record!!")        
    
    def refreshTable(self):
        self.tableDocsDet.clearContents()
        self.tableDocsDet.setRowCount(0)
        self.doc_data_thread = DocDataRetrievalThread()
        self.doc_data_thread.dataRetrieved.connect(self.updateDocTable)
        self.doc_data_thread.start()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 701)
        MainWindow.showMaximized()
        self.admin_activity = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_frame.sizePolicy().hasHeightForWidth())
        self.header_frame.setSizePolicy(sizePolicy)
        self.header_frame.setMinimumSize(QtCore.QSize(1280, 100))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.header_frame.setStyleSheet("background-color:rgb(0, 85, 127);")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_frame = ClickableFrame(self.header_frame)
        self.logo_frame.setMinimumSize(QtCore.QSize(80, 50))
        self.logo_frame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.logo_frame.setStyleSheet("background-color:transparent;\n"
"margin-top:6px;\n"
"margin-bottom:0px;")
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.logo_frame.clicked.connect(self.backHome)
        self.backBtn = QtWidgets.QLabel(self.logo_frame)
        self.backBtn.setGeometry(QtCore.QRect(20, 10, 61, 71))
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backBtn.setStyleSheet("")
        self.backBtn.setText("")
        self.backBtn.setPixmap(QtGui.QPixmap(":/reosurces_logo/back-svgrepo-com.svg"))
        self.backBtn.setScaledContents(True)
        self.backBtn.setAlignment(QtCore.Qt.AlignCenter)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.logo_frame)
        self.title_frame = QtWidgets.QFrame(self.header_frame)
        self.title_frame.setMinimumSize(QtCore.QSize(1280, 0))
        font = QtGui.QFont()
        font.setPointSize(42)
        self.title_frame.setFont(font)
        self.title_frame.setStyleSheet("background-color:transparent;")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.title_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setMinimumSize(QtCore.QSize(800, 0))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color:#fff;")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.title_frame)
        self.verticalLayout_2.addWidget(self.header_frame)
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.activityNameDisp = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.activityNameDisp.setFont(font)
        self.activityNameDisp.setStyleSheet("color:rgb(0, 85, 127);")
        self.activityNameDisp.setObjectName("activityNameDisp")
        self.verticalLayout_22.addWidget(self.activityNameDisp, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(15, 9, 15, -1)
        self.gridLayout_2.setHorizontalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableDocsDet = QtWidgets.QTableWidget(self.frame)
        self.tableDocsDet.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableDocsDet.setFont(font)
        self.tableDocsDet.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableDocsDet.setStyleSheet("QHeaderView::section {\n"
"                background-color: #00557d;\n"
"                color: white;\n"
"                font-weight: bold;\n"
"padding:5px;\n"
"            }")
        self.tableDocsDet.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableDocsDet.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableDocsDet.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableDocsDet.setShowGrid(True)
        self.tableDocsDet.setWordWrap(False)
        self.tableDocsDet.setObjectName("tableDocsDet")
        self.tableDocsDet.setColumnCount(11)
        self.tableDocsDet.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 85, 125))
        self.tableDocsDet.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocsDet.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocsDet.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocsDet.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocsDet.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocsDet.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocsDet.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocsDet.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocsDet.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocsDet.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocsDet.setHorizontalHeaderItem(10, item)
        self.tableDocsDet.horizontalHeader().setCascadingSectionResizes(True)
        self.tableDocsDet.horizontalHeader().setDefaultSectionSize(180)
        self.tableDocsDet.verticalHeader().setDefaultSectionSize(45)
        self.gridLayout_2.addWidget(self.tableDocsDet, 1, 0, 3, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("BACKGROUND-COLOR:#c8cbcf;\n"
"BORDER-RADIUS:5PX;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("padding-right:2px;\n"
"padding-left:2px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setHorizontalSpacing(25)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.docExpEntry = QtWidgets.QTextEdit(self.frame_5)
        self.docExpEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.docExpEntry.setFont(font)
        self.docExpEntry.setStyleSheet("background-color:white;")
        self.docExpEntry.setObjectName("docExpEntry")
        self.gridLayout.addWidget(self.docExpEntry, 3, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.docGenEntry = QtWidgets.QTextEdit(self.frame_5)
        self.docGenEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.docGenEntry.setFont(font)
        self.docGenEntry.setStyleSheet("background-color:white;")
        self.docGenEntry.setObjectName("docGenEntry")
        self.gridLayout.addWidget(self.docGenEntry, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.docNameEntry = QtWidgets.QTextEdit(self.frame_5)
        self.docNameEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.docNameEntry.setFont(font)
        self.docNameEntry.setStyleSheet("background-color:white;")
        self.docNameEntry.setObjectName("docNameEntry")
        self.gridLayout.addWidget(self.docNameEntry, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.docAgeEntry = QtWidgets.QTextEdit(self.frame_5)
        self.docAgeEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.docAgeEntry.setFont(font)
        self.docAgeEntry.setStyleSheet("background-color:white;")
        self.docAgeEntry.setObjectName("docAgeEntry")
        self.gridLayout.addWidget(self.docAgeEntry, 2, 3, 1, 1)
        self.docSpecialityEntry = QtWidgets.QTextEdit(self.frame_5)
        self.docSpecialityEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.docSpecialityEntry.setFont(font)
        self.docSpecialityEntry.setStyleSheet("background-color:white;")
        self.docSpecialityEntry.setObjectName("docSpecialityEntry")
        self.gridLayout.addWidget(self.docSpecialityEntry, 4, 1, 1, 1)
        self.docFeeEntry = QtWidgets.QTextEdit(self.frame_5)
        self.docFeeEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.docFeeEntry.setFont(font)
        self.docFeeEntry.setStyleSheet("background-color:white;")
        self.docFeeEntry.setObjectName("docFeeEntry")
        self.gridLayout.addWidget(self.docFeeEntry, 7, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 0, 1, 1)
        self.docStatusEntry = QtWidgets.QTextEdit(self.frame_5)
        self.docStatusEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.docStatusEntry.setFont(font)
        self.docStatusEntry.setStyleSheet("background-color:white;")
        self.docStatusEntry.setObjectName("docStatusEntry")
        self.gridLayout.addWidget(self.docStatusEntry, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 2, 1, 1)
        self.doc_appntsEntry = QtWidgets.QTextEdit(self.frame_5)
        self.doc_appntsEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doc_appntsEntry.setFont(font)
        self.doc_appntsEntry.setStyleSheet("background-color:white;")
        self.doc_appntsEntry.setObjectName("doc_appntsEntry")
        self.gridLayout.addWidget(self.doc_appntsEntry, 7, 3, 1, 1)
        self.docDeptEntry = QtWidgets.QTextEdit(self.frame_5)
        self.docDeptEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.docDeptEntry.setFont(font)
        self.docDeptEntry.setStyleSheet("background-color:white;")
        self.docDeptEntry.setObjectName("docDeptEntry")
        self.gridLayout.addWidget(self.docDeptEntry, 4, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 7, 2, 1, 1)
        self.licenseNoEntry = QtWidgets.QTextEdit(self.frame_5)
        self.licenseNoEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.licenseNoEntry.setFont(font)
        self.licenseNoEntry.setStyleSheet("background-color:white;")
        self.licenseNoEntry.setObjectName("licenseNoEntry")
        self.gridLayout.addWidget(self.licenseNoEntry, 0, 1, 1, 1)
        self.docTimeSlotEntry = QtWidgets.QTextEdit(self.frame_5)
        self.docTimeSlotEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.docTimeSlotEntry.setFont(font)
        self.docTimeSlotEntry.setStyleSheet("background-color:white;")
        self.docTimeSlotEntry.setObjectName("docTimeSlotEntry")
        self.gridLayout.addWidget(self.docTimeSlotEntry, 8, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 8, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.gridLayout_2.addWidget(self.frame_3, 1, 1, 1, 2)
        self.addDocBtn = QtWidgets.QPushButton(self.frame)
        self.addDocBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addDocBtn.setFont(font)
        self.addDocBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addDocBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.addDocBtn.setObjectName("addDocBtn")
        self.gridLayout_2.addWidget(self.addDocBtn, 2, 1, 1, 1)
        self.updtDocBtn = QtWidgets.QPushButton(self.frame)
        self.updtDocBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updtDocBtn.setFont(font)
        self.updtDocBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updtDocBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.updtDocBtn.setObjectName("updtDocBtn")
        self.gridLayout_2.addWidget(self.updtDocBtn, 2, 2, 1, 1)
        self.delDocBtn = QtWidgets.QPushButton(self.frame)
        self.delDocBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delDocBtn.setFont(font)
        self.delDocBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delDocBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.delDocBtn.setObjectName("delDocBtn")
        self.gridLayout_2.addWidget(self.delDocBtn, 3, 1, 1, 2)
        self.verticalLayout_2.addWidget(self.frame)

        self.addDocBtn.clicked.connect(self.addData)
        self.updtDocBtn.clicked.connect(self.updtData)
        self.delDocBtn.clicked.connect(self.delData)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "HOSPITAL MANAGEMENT SYSTEM"))
        self.activityNameDisp.setText(_translate("MainWindow", "DOCTORS"))
        self.tableDocsDet.setSortingEnabled(True)
        item = self.tableDocsDet.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "LICENSE NO"))
        item = self.tableDocsDet.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.tableDocsDet.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "STATUS"))
        item = self.tableDocsDet.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "AGE"))
        item = self.tableDocsDet.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "GENDER"))
        item = self.tableDocsDet.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "EXP"))
        item = self.tableDocsDet.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "SPECIALITY"))
        item = self.tableDocsDet.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "DEPT"))
        item = self.tableDocsDet.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "FEE"))
        item = self.tableDocsDet.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "APPNT DAYS"))
        item = self.tableDocsDet.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "TIME SLOT"))
        self.label.setText(_translate("MainWindow", "DOCTOR FORM"))
        self.label_5.setText(_translate("MainWindow", "AGE:"))
        self.label_8.setText(_translate("MainWindow", "EXPERIENCE:"))
        self.label_4.setText(_translate("MainWindow", "STATUS:"))
        self.label_9.setText(_translate("MainWindow", "SPECIALITY:"))
        self.label_3.setText(_translate("MainWindow", "NAME :"))
        self.label_2.setText(_translate("MainWindow", "LICENSE NO :"))
        self.label_11.setText(_translate("MainWindow", "FEE:"))
        self.label_10.setText(_translate("MainWindow", "DEPARTMENT:"))
        self.label_7.setText(_translate("MainWindow", "GENDER:"))
        self.label_12.setText(_translate("MainWindow", "APPNT DAYS:"))
        self.label_13.setText(_translate("MainWindow", "TIME SLOT:"))
        self.addDocBtn.setText(_translate("MainWindow", "ADD"))
        self.updtDocBtn.setText(_translate("MainWindow", "UPDATE"))
        self.delDocBtn.setText(_translate("MainWindow", "DELETE"))
import resources_rc
