# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_depts_lay.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from clickableFrame import ClickableFrame
from database import ConnectionPool,showDeptsData,addDeptData,updtDeptData,deleteDeptData
from EntryChecking import *
from utils import getSelectedRowData

class DeptDataRetrievalThread(QtCore.QThread):
    dataRetrieved = QtCore.pyqtSignal(object)
    retrievalComplete = QtCore.pyqtSignal()
    def __init__(self, parent=None):
        super(DeptDataRetrievalThread, self).__init__(parent)

    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                data = showDeptsData(pool)
                self.dataRetrieved.emit(data)
        except Exception as e:
            print(e)

class AddUpdateDelDeptDataThread(QtCore.QThread):
    operationComplete = QtCore.pyqtSignal()
    def __init__(self,data,flag,parent=None):
        super(AddUpdateDelDeptDataThread, self).__init__(parent)
        self.flag=flag
        self.data=data
    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                if(self.flag==1):
                     addDeptData(pool,self.data)
                elif(self.flag==2):
                     updtDeptData(pool,self.data)
                elif(self.flag==3):
                     deleteDeptData(pool,self.data)
                self.operationComplete.emit()

        except Exception as e:
            print(e)

class Admin_depts(object):
    
    def __init__(self):
        self.deptIdEntry = QtWidgets.QTextEdit()
        self.deptNameEntry = QtWidgets.QTextEdit()
        self.deptDocCountEntry = QtWidgets.QTextEdit()
        self.deptNursesCountEntry = QtWidgets.QTextEdit()
        self.deptStaffCountEntry = QtWidgets.QTextEdit()
        self.deptEstdDateEntry = QtWidgets.QTextEdit()
        self.deptStatusEntry = QtWidgets.QTextEdit()
        self.tableDeptsDet = QtWidgets.QTableWidget()
        self.dept_data_thread = DeptDataRetrievalThread()
        self.dept_data_thread.dataRetrieved.connect(self.updateDeptTable)
        self.dept_data_thread.start()
    
    def backHome(self):
        from Admin_homepage_lay import Admin_home_lay
        self.window = QtWidgets.QMainWindow()
        self.ui = Admin_home_lay()
        self.ui.setupUi(self.window)
        self.window.show()
        self.admin_activity.close()

    def updateDeptTable(self,data):
        self.dept_data_thread.retrievalComplete.connect(self.dept_data_thread.quit)
        for row_number, row_data in enumerate(data):
            self.tableDeptsDet.insertRow(row_number)
            for column_number, column_data in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(column_data))
                self.tableDeptsDet.setItem(row_number, column_number, item)

    def showWarningMessage(self,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle("Warning")
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def verifyData(self,data):
        if not checkEmptyFields(data):
                self.showWarningMessage("All Fields are mandatory!!")
        else:
                if checkNumericalData(data[0]) and checkNumericalData(data[2]) and checkNumericalData(data[3]) and checkNumericalData(data[4]):
                        if checkLicenseNumber(data[0],self.tableDeptsDet):
                             return True
                        else:
                             self.showWarningMessage("Dept id already in use!!")
                else:
                     self.showWarningMessage("Number field error!!")
        return False

    def addData(self):
        data = (self.deptIdEntry.toPlainText().strip(),self.deptNameEntry.toPlainText().strip(),
                self.deptDocCountEntry.toPlainText().strip(),self.deptNursesCountEntry.toPlainText().strip(),
                self.deptStaffCountEntry.toPlainText().strip(),self.deptEstdDateEntry.toPlainText().strip(),
                self.deptStatusEntry.toPlainText().strip())
        if self.verifyData(data):
                self.dept_data_thread = AddUpdateDelDeptDataThread(data,flag=1)
                self.dept_data_thread.start()
                self.dept_data_thread.operationComplete.connect(self.refreshTable)
        else:
             self.showWarningMessage("Operation failed!!")

    def verifyUpdtData(self,data):
        if not checkEmptyFields(data):
                self.showWarningMessage("All Fields are mandatory!!")
        else:
                if checkNumericalData(data[0]) and checkNumericalData(data[2]) and checkNumericalData(data[3]) and checkNumericalData(data[4]):
                        row = getSelectedRowData(self.tableDeptsDet)
                        if row is not None and str(row[0]) == str(data[0]):
                                return True
                        else:
                                self.showWarningMessage("Please select correct record!!")
                else:
                     self.showWarningMessage("Number field error!!")

    def updtData(self):
        data = (self.deptIdEntry.toPlainText().strip(),self.deptNameEntry.toPlainText().strip(),
                self.deptDocCountEntry.toPlainText().strip(),self.deptNursesCountEntry.toPlainText().strip(),
                self.deptStaffCountEntry.toPlainText().strip(),self.deptEstdDateEntry.toPlainText().strip(),
                self.deptStatusEntry.toPlainText().strip())
        if self.verifyUpdtData(data):
                row = getSelectedRowData(self.tableDeptsDet)
                data = (self.deptIdEntry.toPlainText().strip(),self.deptNameEntry.toPlainText().strip(),
                self.deptDocCountEntry.toPlainText().strip(),self.deptNursesCountEntry.toPlainText().strip(),
                self.deptStaffCountEntry.toPlainText().strip(),self.deptEstdDateEntry.toPlainText().strip(),
                self.deptStatusEntry.toPlainText().strip(),row[0])
                self.dept_data_thread = AddUpdateDelDeptDataThread(data,flag=2)
                self.dept_data_thread.start()
                self.dept_data_thread.operationComplete.connect(self.refreshTable)
        else:
             self.showWarningMessage("Operation failed!!")

    def delData(self):
        row = getSelectedRowData(self.tableDeptsDet)
        if row is not None:
                selected_id_no = row[0]
                self.dept_data_thread = AddUpdateDelDeptDataThread(selected_id_no,flag=3)
                self.dept_data_thread.start()
                self.dept_data_thread.operationComplete.connect(self.refreshTable)
        else:
             self.showWarningMessage("Please select record!!")

    def refreshTable(self):
        self.tableDeptsDet.clearContents()
        self.tableDeptsDet.setRowCount(0)
        self.dept_data_thread = DeptDataRetrievalThread()
        self.dept_data_thread.dataRetrieved.connect(self.updateDeptTable)
        self.dept_data_thread.start()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 701)
        MainWindow.showMaximized()
        self.admin_activity = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_frame.sizePolicy().hasHeightForWidth())
        self.header_frame.setSizePolicy(sizePolicy)
        self.header_frame.setMinimumSize(QtCore.QSize(1280, 100))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.header_frame.setStyleSheet("background-color:rgb(0, 85, 127);")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_frame = ClickableFrame(self.header_frame)
        self.logo_frame.setMinimumSize(QtCore.QSize(80, 50))
        self.logo_frame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.logo_frame.setStyleSheet("background-color:transparent;\n"
"margin-top:6px;\n"
"margin-bottom:0px;")
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.logo_frame.clicked.connect(self.backHome)
        self.backBtn = QtWidgets.QLabel(self.logo_frame)
        self.backBtn.setGeometry(QtCore.QRect(20, 10, 61, 71))
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backBtn.setStyleSheet("")
        self.backBtn.setText("")
        self.backBtn.setPixmap(QtGui.QPixmap(":/reosurces_logo/back-svgrepo-com.svg"))
        self.backBtn.setScaledContents(True)
        self.backBtn.setAlignment(QtCore.Qt.AlignCenter)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.logo_frame)
        self.title_frame = QtWidgets.QFrame(self.header_frame)
        self.title_frame.setMinimumSize(QtCore.QSize(1280, 0))
        font = QtGui.QFont()
        font.setPointSize(42)
        self.title_frame.setFont(font)
        self.title_frame.setStyleSheet("background-color:transparent;")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.title_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setMinimumSize(QtCore.QSize(800, 0))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color:#fff;")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.title_frame)
        self.verticalLayout_2.addWidget(self.header_frame)
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.activityNameDisp = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.activityNameDisp.setFont(font)
        self.activityNameDisp.setStyleSheet("color:rgb(0, 85, 127);")
        self.activityNameDisp.setObjectName("activityNameDisp")
        self.verticalLayout_22.addWidget(self.activityNameDisp, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(15, 9, 15, -1)
        self.gridLayout_2.setHorizontalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("BACKGROUND-COLOR:#c8cbcf;\n"
"BORDER-RADIUS:5PX;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("padding-right:2px;\n"
"padding-left:2px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setHorizontalSpacing(25)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.deptStaffCountEntry = QtWidgets.QTextEdit(self.frame_5)
        self.deptStaffCountEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deptStaffCountEntry.setFont(font)
        self.deptStaffCountEntry.setStyleSheet("background-color:white;")
        self.deptStaffCountEntry.setObjectName("deptStaffCountEntry")
        self.gridLayout.addWidget(self.deptStaffCountEntry, 3, 1, 1, 1)
        self.deptNameEntry = QtWidgets.QTextEdit(self.frame_5)
        self.deptNameEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deptNameEntry.setFont(font)
        self.deptNameEntry.setStyleSheet("background-color:white;")
        self.deptNameEntry.setObjectName("deptNameEntry")
        self.gridLayout.addWidget(self.deptNameEntry, 0, 3, 1, 1)
        self.deptNursesCountEntry = QtWidgets.QTextEdit(self.frame_5)
        self.deptNursesCountEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deptNursesCountEntry.setFont(font)
        self.deptNursesCountEntry.setStyleSheet("background-color:white;")
        self.deptNursesCountEntry.setObjectName("deptNursesCountEntry")
        self.gridLayout.addWidget(self.deptNursesCountEntry, 2, 3, 1, 1)
        self.deptStatusEntry = QtWidgets.QTextEdit(self.frame_5)
        self.deptStatusEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deptStatusEntry.setFont(font)
        self.deptStatusEntry.setStyleSheet("background-color:white;")
        self.deptStatusEntry.setObjectName("deptStatusEntry")
        self.gridLayout.addWidget(self.deptStatusEntry, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.deptEstdDateEntry = QtWidgets.QTextEdit(self.frame_5)
        self.deptEstdDateEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deptEstdDateEntry.setFont(font)
        self.deptEstdDateEntry.setStyleSheet("background-color:white;")
        self.deptEstdDateEntry.setObjectName("deptEstdDateEntry")
        self.gridLayout.addWidget(self.deptEstdDateEntry, 3, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.deptIdEntry = QtWidgets.QTextEdit(self.frame_5)
        self.deptIdEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deptIdEntry.setFont(font)
        self.deptIdEntry.setStyleSheet("background-color:white;")
        self.deptIdEntry.setObjectName("deptIdEntry")
        self.gridLayout.addWidget(self.deptIdEntry, 0, 1, 1, 1)
        self.deptDocCountEntry = QtWidgets.QTextEdit(self.frame_5)
        self.deptDocCountEntry.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deptDocCountEntry.setFont(font)
        self.deptDocCountEntry.setStyleSheet("background-color:white;")
        self.deptDocCountEntry.setObjectName("deptDocCountEntry")
        self.gridLayout.addWidget(self.deptDocCountEntry, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.gridLayout_2.addWidget(self.frame_3, 0, 1, 1, 2)
        self.delDeptBtn = QtWidgets.QPushButton(self.frame)
        self.delDeptBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delDeptBtn.setFont(font)
        self.delDeptBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delDeptBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.delDeptBtn.setObjectName("delDeptBtn")
        self.gridLayout_2.addWidget(self.delDeptBtn, 2, 1, 1, 2)
        self.addDeptBtn = QtWidgets.QPushButton(self.frame)
        self.addDeptBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addDeptBtn.setFont(font)
        self.addDeptBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addDeptBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.addDeptBtn.setObjectName("addDeptBtn")
        self.gridLayout_2.addWidget(self.addDeptBtn, 1, 1, 1, 1)
        self.tableDeptsDet = QtWidgets.QTableWidget(self.frame)
        self.tableDeptsDet.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableDeptsDet.setFont(font)
        self.tableDeptsDet.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableDeptsDet.setStyleSheet("QHeaderView::section {\n"
"                background-color: #00557d;\n"
"                color: white;\n"
"                font-weight: bold;\n"
"padding:5px;\n"
"            }")
        self.tableDeptsDet.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableDeptsDet.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableDeptsDet.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableDeptsDet.setShowGrid(True)
        self.tableDeptsDet.setWordWrap(False)
        self.tableDeptsDet.setObjectName("tableDeptsDet")
        self.tableDeptsDet.setColumnCount(7)
        self.tableDeptsDet.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 85, 125))
        self.tableDeptsDet.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDeptsDet.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDeptsDet.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDeptsDet.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDeptsDet.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDeptsDet.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDeptsDet.setHorizontalHeaderItem(6, item)
        self.tableDeptsDet.horizontalHeader().setCascadingSectionResizes(True)
        self.tableDeptsDet.horizontalHeader().setDefaultSectionSize(180)
        self.tableDeptsDet.verticalHeader().setDefaultSectionSize(45)
        self.gridLayout_2.addWidget(self.tableDeptsDet, 0, 0, 3, 1)
        self.updtDeptBtn = QtWidgets.QPushButton(self.frame)
        self.updtDeptBtn.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updtDeptBtn.setFont(font)
        self.updtDeptBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updtDeptBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.updtDeptBtn.setObjectName("updtDeptBtn")
        self.gridLayout_2.addWidget(self.updtDeptBtn, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)

        self.addDeptBtn.clicked.connect(self.addData)
        self.updtDeptBtn.clicked.connect(self.updtData)
        self.delDeptBtn.clicked.connect(self.delData)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "HOSPITAL MANAGEMENT SYSTEM"))
        self.activityNameDisp.setText(_translate("MainWindow", "DEPARTMENTS"))
        self.label.setText(_translate("MainWindow", "DEPARTMENT FORM"))
        self.label_4.setText(_translate("MainWindow", "DOCTORS:"))
        self.label_5.setText(_translate("MainWindow", "NURSES:"))
        self.label_8.setText(_translate("MainWindow", "ESTD DATE:"))
        self.label_7.setText(_translate("MainWindow", "STAFF:"))
        self.label_3.setText(_translate("MainWindow", "NAME :"))
        self.label_2.setText(_translate("MainWindow", "DEPT ID: "))
        self.label_9.setText(_translate("MainWindow", "STATUS"))
        self.delDeptBtn.setText(_translate("MainWindow", "DELETE"))
        self.addDeptBtn.setText(_translate("MainWindow", "ADD"))
        self.tableDeptsDet.setSortingEnabled(True)
        item = self.tableDeptsDet.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DEPARTMENT ID"))
        item = self.tableDeptsDet.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.tableDeptsDet.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DOCTORS"))
        item = self.tableDeptsDet.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "NURSES"))
        item = self.tableDeptsDet.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "STAFF"))
        item = self.tableDeptsDet.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ESTD DATE"))
        item = self.tableDeptsDet.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "STATUS"))
        self.updtDeptBtn.setText(_translate("MainWindow", "UPDATE"))
import resources_rc
