# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_emegency_form_lay.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from clickableFrame import ClickableFrame
from database import ConnectionPool,showEmergencyBedsData,updateAllotmentBedData,updateBedStatus
from utils import getCurrDate,getSelectedRowData,getCurrTime
from math import floor

class EmergencyBedDataRetrivalThread(QtCore.QThread):
    dataRetrieved = QtCore.pyqtSignal(object)
    retrievalComplete = QtCore.pyqtSignal()
    def __init__(self, parent=None):
        super(EmergencyBedDataRetrivalThread, self).__init__(parent)

    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                data = showEmergencyBedsData(pool)
                self.dataRetrieved.emit(data)
                self.retrievalComplete.emit()
        except Exception as e:
            print(e)

class Client_emergency_form(object):
    
    def __init__(self):
        self.tableEmergencyBeds = QtWidgets.QTableWidget()
        self.patAddrEntry = QtWidgets.QLineEdit()
        self.patNameEntry = QtWidgets.QLineEdit()
        self.patAgeEntry = QtWidgets.QLineEdit()
        self.patGenderEntry = QtWidgets.QLineEdit()
        self.patPhoneEntry = QtWidgets.QLineEdit()
        self.patReasonEntry = QtWidgets.QLineEdit()
        self.emergency_beds_data_thread = EmergencyBedDataRetrivalThread()
        self.emergency_beds_data_thread.dataRetrieved.connect(self.updateEmerBedTable)
        self.emergency_beds_data_thread.start()
    
    def goHome(self):
        from Client_homepage_lay import Client_home_lay
        self.window = QtWidgets.QMainWindow()
        self.ui = Client_home_lay()
        self.ui.setupUi(self.window)
        self.window.show()
        self.client_activity.close()

    def updateEmerBedTable(self,data):
        self.emergency_beds_data_thread.retrievalComplete.connect(self.emergency_beds_data_thread.quit)
        for row_number, row_data in enumerate(data):
            self.tableEmergencyBeds.insertRow(row_number)
            for column_number, column_data in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(column_data))
                self.tableEmergencyBeds.setItem(row_number, column_number, item)
    
    def showWarningMessage(self,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle("Warning")
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def dataCheck(self):
        if ((len(self.patAddrEntry.text().strip())==0) or (len(self.patNameEntry.text().strip())==0) or
            (len(self.patAgeEntry.text().strip())==0) or (len(self.patGenderEntry.text().strip())==0) or 
            (len(self.patPhoneEntry.text().strip())==0) or (len(self.patReasonEntry.text().strip())==0)):
            self.showWarningMessage("All fields are mandatory!!")
        else:
            for i in self.patPhoneEntry.text().strip():
                if i.isalpha() or len(self.patPhoneEntry.text().strip())<10 or len(self.patPhoneEntry.text().strip())>10:
                    self.showWarningMessage("Phone number wrong!!")
                    return False
            if int(self.patPhoneEntry.text().strip())<=0:
                    self.showWarningMessage("Phone number wrong!!")
                    return False
            if self.patAgeEntry.text().strip().isalpha() or (self.patAgeEntry.text().strip().isalnum() and not self.patAgeEntry.text().strip().isdigit()):
                print("hi")
                self.showWarningMessage("Wrong Age Entry!!")
                return False
            elif int(floor(float(self.patAgeEntry.text().strip())))<=0:
                print("hey")
                self.showWarningMessage("Wrong Age Entry!!")
                return False
            return True

    def allotBed(self):
        if self.dataCheck():
            data = getSelectedRowData(self.tableEmergencyBeds)
            if data==None:
                self.showWarningMessage("Please choose the bed!!")
            else:
                processed_data = (self.patNameEntry.text(),self.patReasonEntry.text(),getCurrDate(),getCurrTime(),
                                  self.patGenderEntry.text(),self.patAgeEntry.text(),self.patAddrEntry.text(),
                                  self.patPhoneEntry.text(),data[0])
                pool = ConnectionPool(5, 'hms_database.db')
                updateAllotmentBedData(pool,processed_data)
                updateBedStatus(pool)
                self.refreshTable()
                

    def releaseBed(self):
        data = getSelectedRowData(self.tableEmergencyBeds)
        if data==None:
                self.showWarningMessage("Please choose the bed!!")
        else:
                pool = ConnectionPool(5, 'hms_database.db')
                processed_data = ('NA','NA','NA','NA','NA','NA','NA','NA',data[0])
                updateAllotmentBedData(pool,processed_data)
                updateBedStatus(pool)
                self.refreshTable()

    def refreshTable(self):
        self.tableEmergencyBeds.clearContents()
        self.tableEmergencyBeds.setRowCount(0)
        self.appt_data_thread = EmergencyBedDataRetrivalThread()
        self.appt_data_thread.dataRetrieved.connect(self.updateEmerBedTable)
        self.appt_data_thread.start()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 700)
        MainWindow.showMaximized()
        self.client_activity = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_frame.sizePolicy().hasHeightForWidth())
        self.header_frame.setSizePolicy(sizePolicy)
        self.header_frame.setMinimumSize(QtCore.QSize(1280, 100))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.header_frame.setStyleSheet("background-color:rgb(0, 85, 127);")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_frame = ClickableFrame(self.header_frame)
        self.logo_frame.setMinimumSize(QtCore.QSize(80, 50))
        self.logo_frame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.logo_frame.setStyleSheet("background-color:transparent;\n"
"margin-top:6px;\n"
"margin-bottom:0px;")
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.logo_frame.clicked.connect(self.goHome)
        self.backBtn = QtWidgets.QLabel(self.logo_frame)
        self.backBtn.setGeometry(QtCore.QRect(20, 10, 61, 71))
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backBtn.setStyleSheet("")
        self.backBtn.setText("")
        self.backBtn.setPixmap(QtGui.QPixmap(":/reosurces_logo/back-svgrepo-com.svg"))
        self.backBtn.setScaledContents(True)
        self.backBtn.setAlignment(QtCore.Qt.AlignCenter)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.logo_frame)
        self.title_frame = QtWidgets.QFrame(self.header_frame)
        self.title_frame.setMinimumSize(QtCore.QSize(1280, 0))
        font = QtGui.QFont()
        font.setPointSize(42)
        self.title_frame.setFont(font)
        self.title_frame.setStyleSheet("background-color:transparent;")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.title_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setMinimumSize(QtCore.QSize(800, 0))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color:#fff;")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.title_frame)
        self.verticalLayout_2.addWidget(self.header_frame)
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_19 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:rgb(0, 85, 127);")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_22.addWidget(self.label_19, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_2.setHorizontalSpacing(25)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableEmergencyBeds = QtWidgets.QTableWidget(self.frame_8)
        self.tableEmergencyBeds.setStyleSheet("QHeaderView::section {\n"
"                background-color: #00557d;\n"
"                color: white;\n"
"                font-weight: bold;\n"
"padding:5px;\n"
"            }")
        self.tableEmergencyBeds.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableEmergencyBeds.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableEmergencyBeds.setWordWrap(False)
        self.tableEmergencyBeds.setObjectName("tableEmergencyBeds")
        self.tableEmergencyBeds.setColumnCount(9)
        self.tableEmergencyBeds.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmergencyBeds.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmergencyBeds.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmergencyBeds.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmergencyBeds.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmergencyBeds.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmergencyBeds.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmergencyBeds.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmergencyBeds.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmergencyBeds.setHorizontalHeaderItem(8, item)
        self.tableEmergencyBeds.horizontalHeader().setDefaultSectionSize(160)
        self.gridLayout_2.addWidget(self.tableEmergencyBeds, 0, 0, 1, 1)
        self.allotBedBtn = QtWidgets.QPushButton(self.frame_8)
        self.allotBedBtn.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.allotBedBtn.setFont(font)
        self.allotBedBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.allotBedBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.allotBedBtn.setObjectName("allotBedBtn")
        self.allotBedBtn.clicked.connect(self.allotBed)
        self.gridLayout_2.addWidget(self.allotBedBtn, 2, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_8)
        self.frame.setStyleSheet("BACKGROUND-COLOR:#c8cbcf;\n"
"BORDER-RADIUS:5PX;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(10, 0, 10, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.patGenderEntry = QtWidgets.QLineEdit(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patGenderEntry.setFont(font)
        self.patGenderEntry.setStyleSheet("BORDER-RADIUS:5PX;\n"
"PADDING:5PX;\n"
"COLOR:BLACK;\n"
"BACKGROUND-COLOR:WHITE;")
        self.patGenderEntry.setObjectName("patGenderEntry")
        self.horizontalLayout_3.addWidget(self.patGenderEntry)
        self.horizontalLayout_16.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.patAgeEntry = QtWidgets.QLineEdit(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patAgeEntry.setFont(font)
        self.patAgeEntry.setStyleSheet("BORDER-RADIUS:5PX;\n"
"PADDING:5PX;\n"
"COLOR:BLACK;\n"
"BACKGROUND-COLOR:WHITE;")
        self.patAgeEntry.setObjectName("patAgeEntry")
        self.horizontalLayout_4.addWidget(self.patAgeEntry)
        self.horizontalLayout_16.addWidget(self.frame_6)
        self.gridLayout.addWidget(self.frame_4, 2, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("COLOR:BLACK;")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.patNameEntry = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patNameEntry.setFont(font)
        self.patNameEntry.setStyleSheet("BORDER-RADIUS:5PX;\n"
"PADDING:5PX;\n"
"COLOR:BLACK;\n"
"BACKGROUND-COLOR:WHITE;")
        self.patNameEntry.setObjectName("patNameEntry")
        self.horizontalLayout_2.addWidget(self.patNameEntry)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.patAddrEntry = QtWidgets.QLineEdit(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patAddrEntry.setFont(font)
        self.patAddrEntry.setStyleSheet("BORDER-RADIUS:5PX;\n"
"PADDING:5PX;\n"
"COLOR:BLACK;\n"
"BACKGROUND-COLOR:WHITE;")
        self.patAddrEntry.setObjectName("patAddrEntry")
        self.horizontalLayout_9.addWidget(self.patAddrEntry)
        self.gridLayout.addWidget(self.frame_10, 4, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.patPhoneEntry = QtWidgets.QLineEdit(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patPhoneEntry.setFont(font)
        self.patPhoneEntry.setStyleSheet("BORDER-RADIUS:5PX;\n"
"PADDING:5PX;\n"
"COLOR:BLACK;\n"
"BACKGROUND-COLOR:WHITE;")
        self.patPhoneEntry.setObjectName("patPhoneEntry")
        self.horizontalLayout_7.addWidget(self.patPhoneEntry)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.gridLayout.addWidget(self.frame_7, 3, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.patReasonEntry = QtWidgets.QLineEdit(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patReasonEntry.setFont(font)
        self.patReasonEntry.setStyleSheet("BORDER-RADIUS:5PX;\n"
"PADDING:5PX;\n"
"COLOR:BLACK;\n"
"BACKGROUND-COLOR:WHITE;")
        self.patReasonEntry.setObjectName("patReasonEntry")
        self.horizontalLayout_10.addWidget(self.patReasonEntry)
        self.gridLayout.addWidget(self.frame_11, 5, 0, 1, 1)
        self.frame_16 = QtWidgets.QFrame(self.frame)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_16.setStyleSheet("COLOR:WHITE;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_23.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_20 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_23.addWidget(self.label_20, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addWidget(self.frame_16, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 1, 1, 1)
        self.releaseBedBtn = QtWidgets.QPushButton(self.frame_8)
        self.releaseBedBtn.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.releaseBedBtn.setFont(font)
        self.releaseBedBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.releaseBedBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.releaseBedBtn.setObjectName("releaseBedBtn")
        self.releaseBedBtn.clicked.connect(self.releaseBed)
        self.gridLayout_2.addWidget(self.releaseBedBtn, 1, 0, 2, 1)
        self.verticalLayout_2.addWidget(self.frame_8)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "HOSPITAL MANAGEMENT SYSTEM"))
        self.label_19.setText(_translate("MainWindow", "EMEGENCY ROOM BED ALLOTMENT"))
        self.tableEmergencyBeds.setSortingEnabled(True)
        item = self.tableEmergencyBeds.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "BED NUMBER"))
        item = self.tableEmergencyBeds.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PATIENT NAME"))
        item = self.tableEmergencyBeds.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "REASON FOR ADMISSION"))
        item = self.tableEmergencyBeds.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "DATE"))
        item = self.tableEmergencyBeds.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "TIME OF ADMISSION"))
        item = self.tableEmergencyBeds.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "GENDER"))
        item = self.tableEmergencyBeds.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "AGE"))
        item = self.tableEmergencyBeds.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "ADDRESS"))
        item = self.tableEmergencyBeds.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "PHONE"))
        self.allotBedBtn.setText(_translate("MainWindow", "ALLOT BED"))
        self.label_2.setText(_translate("MainWindow", "GENDER :"))
        self.patGenderEntry.setPlaceholderText(_translate("MainWindow", "M/F/O"))
        self.label_3.setText(_translate("MainWindow", "AGE :"))
        self.label.setText(_translate("MainWindow", "NAME :"))
        self.patNameEntry.setPlaceholderText(_translate("MainWindow", "Enter patient name"))
        self.label_6.setText(_translate("MainWindow", "ADDRESS :"))
        self.label_5.setText(_translate("MainWindow", "PHONE :"))
        self.patPhoneEntry.setPlaceholderText(_translate("MainWindow", "xxxxxxxxxx"))
        self.label_7.setText(_translate("MainWindow", "REASON FOR ADMISSION :"))
        self.label_20.setText(_translate("MainWindow", "BED ALLOTMENT FORM"))
        self.releaseBedBtn.setText(_translate("MainWindow", "RELEASE BED"))
import resources_rc
