# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_my_appts_lay.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from clickableFrame import ClickableFrame
from database import showDoctorsData,showApptsData,checkHealthInsurance,addApptsData,ConnectionPool,delApptsData
from utils import getSelectedRowData,getCurrDate

class DocDataRetrievalThread(QtCore.QThread):
    dataRetrieved = QtCore.pyqtSignal(object)
    retrievalComplete = QtCore.pyqtSignal()
    def __init__(self, parent=None):
        super(DocDataRetrievalThread, self).__init__(parent)

    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                data = showDoctorsData(pool)
                self.dataRetrieved.emit(data)
                self.retrievalComplete.emit()
        except Exception as e:
            print(e)

class ApptDataRetrievalThread(QtCore.QThread):
    dataRetrieved = QtCore.pyqtSignal(object)
    retrievalComplete = QtCore.pyqtSignal()
    def __init__(self,parent=None):
        super(ApptDataRetrievalThread, self).__init__(parent)

    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                data = showApptsData(pool)
                self.dataRetrieved.emit(data)
                self.retrievalComplete.emit()
        except Exception as e:
            print(e)

class ApptDataInsertionThread(QtCore.QThread):
    dataInserted = QtCore.pyqtSignal()
    def __init__(self,data,parent=None):
        self.data = data
        super(ApptDataInsertionThread, self).__init__(parent)

    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                addApptsData(pool,self.data)
                self.dataInserted.emit()
        except Exception as e:
            print(e)

class ApptDataDeletionThread(QtCore.QThread):
    dataDeleted = QtCore.pyqtSignal()
    def __init__(self,data,parent=None):
        self.data = data
        super(ApptDataDeletionThread, self).__init__(parent)

    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                delApptsData(pool,self.data)
                self.dataDeleted.emit()
        except Exception as e:
            print(e)

class Client_appts(object):
    
    def __init__(self):
        self.tableDocs = QtWidgets.QTableWidget()
        self.tableAppts = QtWidgets.QTableWidget()
        self.patNameEntry = QtWidgets.QTextEdit()
        self.patPhoneEntry = QtWidgets.QTextEdit()
        self.hiNoEntry = QtWidgets.QTextEdit()
        self.doc_data_thread = DocDataRetrievalThread()
        self.appt_data_thread = ApptDataRetrievalThread()
        self.doc_data_thread.dataRetrieved.connect(self.updateDocTable)
        self.appt_data_thread.dataRetrieved.connect(self.updateAppntTable)
        self.doc_data_thread.start()
        self.appt_data_thread.start()
        self.last_row_no=0

    def goHome(self):
        from Client_homepage_lay import Client_home_lay
        self.window = QtWidgets.QMainWindow()
        self.ui = Client_home_lay()
        self.ui.setupUi(self.window)
        self.window.show()
        self.client_activity.close()

    def showWarningMessage(self,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle("Warning")
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def dataCheck(self):
        if ((len(self.patNameEntry.toPlainText().strip())==0) or (len(self.patPhoneEntry.toPlainText().strip())==0) or
            (len(self.hiNoEntry.toPlainText().strip())==0)):
            self.showWarningMessage("All fields are mandatory!!")
        else:
            for i in self.patPhoneEntry.toPlainText().strip():
                if i.isalpha() or len(self.patPhoneEntry.toPlainText().strip())<10 or len(self.patPhoneEntry.toPlainText().strip())>10:
                    self.showWarningMessage("Phone number wrong!!")
                    return False
            if int(self.patPhoneEntry.toPlainText().strip())<=0:
                    self.showWarningMessage("Phone number wrong!!")
                    return False 
            return True

    def verifyHealthInsurance(self):
        if self.dataCheck():
            pool = ConnectionPool(5, 'hms_database.db')
            hi_no = checkHealthInsurance(pool,self.patNameEntry.toPlainText(),self.patPhoneEntry.toPlainText())
            if(str(hi_no) == self.hiNoEntry.toPlainText()):
                self.showWarningMessage("Account Verified and Insurance Number found!!")
            else:
                self.showWarningMessage("Insurance Number not registered!!")    

    def updateDocTable(self,data):
        self.doc_data_thread.retrievalComplete.connect(self.doc_data_thread.quit)
        for row_number, row_data in enumerate(data):
            self.tableDocs.insertRow(row_number)
            for column_number, column_data in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(column_data))
                self.tableDocs.setItem(row_number, column_number, item)

    def updateAppntTable(self,data):
        self.appt_data_thread.retrievalComplete.connect(self.doc_data_thread.quit)
        last_row_no = data[-1][0]
        for row_number, row_data in enumerate(data):
            self.tableAppts.insertRow(row_number)
            for column_number, column_data in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(column_data))
                self.tableAppts.setItem(row_number, column_number, item)
        self.last_row_no = last_row_no+1

    def scheduleAppt(self):
        if self.dataCheck():
                data = getSelectedRowData(self.tableDocs)
                if data==None:
                        self.showWarningMessage("Please choose the Doctor!!")
                else:
                        date = getCurrDate()
                        print(self.last_row_no)
                        processed_data = (self.last_row_no,str(data[1]),self.patNameEntry.toPlainText().strip(),
                                        int(self.patPhoneEntry.toPlainText().strip()),date,str(data[-1]))
                        self.scheApptThread = ApptDataInsertionThread(processed_data)
                        self.last_row_no+=1
                        self.scheApptThread.start()
                        self.scheApptThread.dataInserted.connect(self.refreshTable)

    def deleteAppt(self):
        row = getSelectedRowData(self.tableAppts)
        if row==None:
             self.showWarningMessage("No Row was chosen!!")
        else:
             self.delRowThread = ApptDataDeletionThread(row[0])
             self.delRowThread.start()
             self.delRowThread.dataDeleted.connect(self.refreshTable)
    
    def refreshTable(self):
        self.tableAppts.clearContents()
        self.tableAppts.setRowCount(0)
        self.appt_data_thread = ApptDataRetrievalThread()
        self.appt_data_thread.dataRetrieved.connect(self.updateAppntTable)
        self.appt_data_thread.start()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 701)
        MainWindow.showMaximized()
        self.client_activity = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_frame.sizePolicy().hasHeightForWidth())
        self.header_frame.setSizePolicy(sizePolicy)
        self.header_frame.setMinimumSize(QtCore.QSize(1280, 100))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.header_frame.setStyleSheet("background-color:rgb(0, 85, 127);")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_frame = ClickableFrame(self.header_frame)
        self.logo_frame.setMinimumSize(QtCore.QSize(80, 50))
        self.logo_frame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.logo_frame.setStyleSheet("background-color:transparent;\n"
"margin-top:6px;\n"
"margin-bottom:0px;")
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.logo_frame.clicked.connect(self.goHome)
        self.backBtn = QtWidgets.QLabel(self.logo_frame)
        self.backBtn.setGeometry(QtCore.QRect(20, 10, 61, 71))
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backBtn.setStyleSheet("")
        self.backBtn.setText("")
        self.backBtn.setPixmap(QtGui.QPixmap(":/reosurces_logo/back-svgrepo-com.svg"))
        self.backBtn.setScaledContents(True)
        self.backBtn.setAlignment(QtCore.Qt.AlignCenter)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.logo_frame)
        self.title_frame = QtWidgets.QFrame(self.header_frame)
        self.title_frame.setMinimumSize(QtCore.QSize(1280, 0))
        font = QtGui.QFont()
        font.setPointSize(42)
        self.title_frame.setFont(font)
        self.title_frame.setStyleSheet("background-color:transparent;")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.title_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setMinimumSize(QtCore.QSize(800, 0))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color:#fff;")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.title_frame)
        self.verticalLayout_2.addWidget(self.header_frame)
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_19 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:rgb(0, 85, 127);")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_22.addWidget(self.label_19, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.centralwidget)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_16)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_4.setHorizontalSpacing(25)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.apptIdDisp = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.apptIdDisp.setFont(font)
        self.apptIdDisp.setStyleSheet("color:rgb(0, 85, 127);")
        self.apptIdDisp.setObjectName("apptIdDisp")
        self.gridLayout_4.addWidget(self.apptIdDisp, 1, 4, 1, 2)
        self.hiNoEntry = QtWidgets.QTextEdit(self.frame_4)
        self.hiNoEntry.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hiNoEntry.setFont(font)
        self.hiNoEntry.setObjectName("hiNoEntry")
        self.gridLayout_4.addWidget(self.hiNoEntry, 1, 2, 1, 1)
        self.hiVerifyBtn = QtWidgets.QPushButton(self.frame_4)
        self.hiVerifyBtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.hiVerifyBtn.setFont(font)
        self.hiVerifyBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hiVerifyBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.hiVerifyBtn.setObjectName("hiVerifyBtn")
        self.hiVerifyBtn.clicked.connect(self.verifyHealthInsurance)
        self.gridLayout_4.addWidget(self.hiVerifyBtn, 1, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_4)
        self.label_28.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color:rgb(0, 85, 127);")
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 0, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_4)
        self.label_26.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color:rgb(0, 85, 127);")
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_4)
        self.label_29.setMaximumSize(QtCore.QSize(270, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color:rgb(0, 85, 127);")
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 1, 0, 1, 1)
        self.patNameEntry = QtWidgets.QTextEdit(self.frame_4)
        self.patNameEntry.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patNameEntry.setFont(font)
        self.patNameEntry.setObjectName("patNameEntry")
        self.gridLayout_4.addWidget(self.patNameEntry, 0, 2, 1, 1)
        self.patPhoneEntry = QtWidgets.QTextEdit(self.frame_4)
        self.patPhoneEntry.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patPhoneEntry.setFont(font)
        self.patPhoneEntry.setObjectName("patPhoneEntry")
        self.gridLayout_4.addWidget(self.patPhoneEntry, 0, 4, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_16)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableAppts = QtWidgets.QTableWidget(self.frame)
        self.tableAppts.setStyleSheet("QHeaderView::section {\n"
"                background-color: #00557d;\n"
"                color: white;\n"
"                font-weight: bold;\n"
"padding:5px;\n"
"            }")
        self.tableAppts.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableAppts.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableAppts.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableAppts.setWordWrap(False)
        self.tableAppts.setCornerButtonEnabled(False)
        self.tableAppts.setObjectName("tableAppts")
        self.tableAppts.setColumnCount(6)
        self.tableAppts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableAppts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAppts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAppts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAppts.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAppts.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAppts.setHorizontalHeaderItem(5, item)
        self.tableAppts.horizontalHeader().setDefaultSectionSize(180)
        self.gridLayout_3.addWidget(self.tableAppts, 0, 1, 1, 1)
        self.tableDocs = QtWidgets.QTableWidget(self.frame)
        self.tableDocs.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableDocs.setFont(font)
        self.tableDocs.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableDocs.setStyleSheet("QHeaderView::section {\n"
"                background-color: #00557d;\n"
"                color: white;\n"
"                font-weight: bold;\n"
"padding:5px;\n"
"            }")
        self.tableDocs.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableDocs.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableDocs.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableDocs.setShowGrid(True)
        self.tableDocs.setWordWrap(False)
        self.tableDocs.setObjectName("tableDocs")
        self.tableDocs.setColumnCount(11)
        self.tableDocs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 85, 125))
        self.tableDocs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocs.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocs.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocs.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocs.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocs.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocs.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocs.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocs.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDocs.setHorizontalHeaderItem(10, item)
        self.tableDocs.horizontalHeader().setCascadingSectionResizes(True)
        self.tableDocs.horizontalHeader().setDefaultSectionSize(180)
        self.tableDocs.verticalHeader().setDefaultSectionSize(45)
        self.gridLayout_3.addWidget(self.tableDocs, 0, 0, 1, 1)
        self.schedBtn = QtWidgets.QPushButton(self.frame)
        self.schedBtn.setMinimumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.schedBtn.setFont(font)
        self.schedBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.schedBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.schedBtn.setObjectName("schedBtn")
        self.schedBtn.clicked.connect(self.scheduleAppt)
        self.gridLayout_3.addWidget(self.schedBtn, 1, 0, 1, 1)
        self.remApptsBtn = QtWidgets.QPushButton(self.frame)
        self.remApptsBtn.setMinimumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.remApptsBtn.setFont(font)
        self.remApptsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remApptsBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.remApptsBtn.setObjectName("remApptsBtn")
        self.remApptsBtn.clicked.connect(self.deleteAppt)
        self.gridLayout_3.addWidget(self.remApptsBtn, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "HOSPITAL MANAGEMENT SYSTEM"))
        self.label_19.setText(_translate("MainWindow", "SCHEDULE APPOINTMENT"))
        self.apptIdDisp.setText(_translate("MainWindow", ""))
        self.hiVerifyBtn.setText(_translate("MainWindow", "VERIFY"))
        self.label_28.setText(_translate("MainWindow", "PATIENT PHONE :"))
        self.label_26.setText(_translate("MainWindow", "PATIENT NAME :"))
        self.label_29.setText(_translate("MainWindow", "HEALTH INSURANCE CARD NO:"))
        item = self.tableAppts.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "APPOINTMENT ID"))
        item = self.tableAppts.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DOCTOR NAME"))
        item = self.tableAppts.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PATIENT NAME"))
        item = self.tableAppts.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PATIENT PHONE"))
        item = self.tableAppts.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "DATE"))
        item = self.tableAppts.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "TIME"))
        self.tableDocs.setSortingEnabled(True)
        item = self.tableDocs.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "LICENSE NUMBER"))
        item = self.tableDocs.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DOCTOR NAME"))
        item = self.tableDocs.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "STATUS"))
        item = self.tableDocs.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "AGE IN YRS"))
        item = self.tableDocs.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "GENDER"))
        item = self.tableDocs.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "EXPERIENCE IN YRS"))
        item = self.tableDocs.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "SPECIALITY"))
        item = self.tableDocs.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "DEPARTMENT"))
        item = self.tableDocs.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "FEES"))
        item = self.tableDocs.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "APPOINTMENT DAYS"))
        item = self.tableDocs.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "TIME SLOT"))
        self.schedBtn.setText(_translate("MainWindow", "SCHEDULE"))
        self.remApptsBtn.setText(_translate("MainWindow", "REMOVE"))
import resources_rc


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
