# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_my_orders_lay.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from clickableFrame import ClickableFrame
from database import ConnectionPool,checkHealthInsurance,showMedsData,addPaymentsOrder
from utils import getCurrDate,getSelectedRowData,getCurrTime

class MedsDataRetrivalThread(QtCore.QThread):
    dataRetrieved = QtCore.pyqtSignal(object)
    retrievalComplete = QtCore.pyqtSignal()
    def __init__(self, parent=None):
        super(MedsDataRetrivalThread, self).__init__(parent)

    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                data = showMedsData(pool)
                self.dataRetrieved.emit(data)
                self.retrievalComplete.emit()
        except Exception as e:
            print(e)

class PlaceOrderThread(QtCore.QThread):
    operationComplete = QtCore.pyqtSignal()
    def __init__(self,data=None, parent=None):
        super(PlaceOrderThread, self).__init__(parent)
        self.data = data

    def run(self):
        try:
                pool = ConnectionPool(5, 'hms_database.db')
                addPaymentsOrder(pool,self.data)
                self.operationComplete.emit()
        except Exception as e:
            print(e)

class Client_orders(object):
    
    def __init__(self):
        self.tableMeds = QtWidgets.QTableWidget()
        self.tableOrder = QtWidgets.QTableWidget()
        self.patNameEntry = QtWidgets.QTextEdit()
        self.docNameEntry = QtWidgets.QTextEdit()
        self.patPhoneEntry = QtWidgets.QTextEdit()
        self.lineEdit = QtWidgets.QTextEdit()
        self.hiNoEntry = QtWidgets.QTextEdit()
        self.med_data_thread = MedsDataRetrivalThread()
        self.med_data_thread.dataRetrieved.connect(self.updateMedsTable)
        self.med_data_thread.start()
        self.healthInsuranceWaiver = False
        self.grandTotal = 0
        self.grandTotDisp = QtWidgets.QLabel()
        self.placeOrder_thread = PlaceOrderThread()
    
    def goHome(self):
        from Client_homepage_lay import Client_home_lay
        self.window = QtWidgets.QMainWindow()
        self.ui = Client_home_lay()
        self.ui.setupUi(self.window)
        self.window.show()
        self.client_activity.close()

    def showWarningMessage(self,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle("Warning")
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def dataCheck(self):
        if ((len(self.patNameEntry.toPlainText().strip())==0) or (len(self.patPhoneEntry.toPlainText().strip())==0) or
            (len(self.hiNoEntry.toPlainText().strip())==0) or (len(self.docNameEntry.toPlainText().strip())==0)):
            self.showWarningMessage("All fields are mandatory!!")
        else:
            for i in self.patPhoneEntry.toPlainText().strip():
                if i.isalpha() or len(self.patPhoneEntry.toPlainText().strip())<10 or len(self.patPhoneEntry.toPlainText().strip())>10:
                    self.showWarningMessage("Phone number wrong!!")
                    return False
            if int(self.patPhoneEntry.toPlainText().strip())<=0:
                    self.showWarningMessage("Phone number wrong!!")
                    return False
            return True

    def verifyHealthInsurance(self):
        if self.dataCheck():
            pool = ConnectionPool(5, 'hms_database.db')
            hi_no = checkHealthInsurance(pool,self.patNameEntry.toPlainText().strip(),self.patPhoneEntry.toPlainText().strip())
            if(str(hi_no) == self.hiNoEntry.toPlainText().strip()):
                self.showWarningMessage("Account Verified and Insurance Number found!!")
                self.healthInsuranceWaiver = True
                self.insuranceDisp.setText("100%")
            else:
                self.showWarningMessage("Insurance Number not registered!!")
                self.insuranceDisp.setText("0%")    

    def updateMedsTable(self,data):
        self.med_data_thread.retrievalComplete.connect(self.med_data_thread.quit)
        for row_number, row_data in enumerate(data):
            self.tableMeds.insertRow(row_number)
            for column_number, column_data in enumerate(row_data):
                item = QtWidgets.QTableWidgetItem(str(column_data))
                self.tableMeds.setItem(row_number, column_number, item)

    def addToMyOrder(self):
        if self.dataCheck():
                if len(self.lineEdit.toPlainText().strip())!=0:
                        data = getSelectedRowData(self.tableMeds)
                        if data==None:
                                self.showWarningMessage("Please choose the medicine!!")
                        else:
                                if(int(self.lineEdit.toPlainText().strip())<=int(data[3])):
                                        row_position = self.tableOrder.rowCount()
                                        self.tableOrder.insertRow(row_position)
                                        total_cost = int(self.lineEdit.toPlainText().strip())*int(data[-1])
                                        processed_data = [data[0],data[1],self.lineEdit.toPlainText().strip(),data[-1],str(total_cost)]
                                        col_count=0
                                        for i in processed_data:
                                                item = QtWidgets.QTableWidgetItem(i)
                                                self.tableOrder.setItem(row_position,col_count,item)
                                                col_count+=1
                                        self.updateGrandTotal()
                                else:
                                        self.showWarningMessage("Not enough in Stock!!")
                else:            
                        self.showWarningMessage("Enter no of medicine needed!!")

    def delFromMyOrder(self):
        self.tableOrder.removeRow(self.tableOrder.currentRow())
        self.updateGrandTotal()

    def updateGrandTotal(self):
        total = sum(int(self.tableOrder.item(row, self.tableOrder.columnCount()-1).text()) for row in range(self.tableOrder.rowCount()) if self.tableOrder.item(row, self.tableOrder.columnCount()-1))
        self.grandTotDisp.setText(f"{total}")

    def placeOrder(self):
        if self.dataCheck():
            data = (str(self.tableOrder.rowCount()),self.grandTotDisp.text(),getCurrDate(),getCurrTime())
            self.placeOrder_thread = PlaceOrderThread(data)
            self.placeOrder_thread.operationComplete.connect(self.showBillData)
            self.placeOrder_thread.start()

    def showBillData(self):
        self.placeOrder_thread.quit()
        self.showWarningMessage("Order Success!!")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 701)
        MainWindow.showMaximized()
        self.client_activity = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_frame.sizePolicy().hasHeightForWidth())
        self.header_frame.setSizePolicy(sizePolicy)
        self.header_frame.setMinimumSize(QtCore.QSize(1280, 100))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.header_frame.setStyleSheet("background-color:rgb(0, 85, 127);")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_frame = ClickableFrame(self.header_frame)
        self.logo_frame.setMinimumSize(QtCore.QSize(80, 50))
        self.logo_frame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.logo_frame.setStyleSheet("background-color:transparent;\n"
"margin-top:6px;\n"
"margin-bottom:0px;")
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.logo_frame.clicked.connect(self.goHome)
        self.backBtn = QtWidgets.QLabel(self.logo_frame)
        self.backBtn.setGeometry(QtCore.QRect(20, 10, 61, 71))
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backBtn.setStyleSheet("")
        self.backBtn.setText("")
        self.backBtn.setPixmap(QtGui.QPixmap(":/reosurces_logo/back-svgrepo-com.svg"))
        self.backBtn.setScaledContents(True)
        self.backBtn.setAlignment(QtCore.Qt.AlignCenter)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.logo_frame)
        self.title_frame = QtWidgets.QFrame(self.header_frame)
        self.title_frame.setMinimumSize(QtCore.QSize(1280, 0))
        font = QtGui.QFont()
        font.setPointSize(42)
        self.title_frame.setFont(font)
        self.title_frame.setStyleSheet("background-color:transparent;")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.title_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setMinimumSize(QtCore.QSize(800, 0))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color:#fff;")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.title_frame)
        self.verticalLayout_2.addWidget(self.header_frame)
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_19 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:rgb(0, 85, 127);")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_22.addWidget(self.label_19, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.centralwidget)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.frame_16)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_3.setHorizontalSpacing(25)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_28 = QtWidgets.QLabel(self.frame_4)
        self.label_28.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color:rgb(0, 85, 127);")
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 0, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_4)
        self.label_26.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color:rgb(0, 85, 127);")
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 0, 0, 1, 1)
        self.docNameEntry = QtWidgets.QTextEdit(self.frame_4)
        self.docNameEntry.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.docNameEntry.setFont(font)
        self.docNameEntry.setObjectName("docNameEntry")
        self.gridLayout_3.addWidget(self.docNameEntry, 0, 4, 1, 1)
        self.patNameEntry = QtWidgets.QTextEdit(self.frame_4)
        self.patNameEntry.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patNameEntry.setFont(font)
        self.patNameEntry.setObjectName("patNameEntry")
        self.gridLayout_3.addWidget(self.patNameEntry, 0, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_4)
        self.label_29.setMaximumSize(QtCore.QSize(270, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color:rgb(0, 85, 127);")
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 1, 0, 1, 1)
        self.hiNoEntry = QtWidgets.QTextEdit(self.frame_4)
        self.hiNoEntry.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hiNoEntry.setFont(font)
        self.hiNoEntry.setObjectName("hiNoEntry")
        self.gridLayout_3.addWidget(self.hiNoEntry, 1, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_4)
        self.label_27.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color:rgb(0, 85, 127);")
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 5, 1, 1)
        self.patPhoneEntry = QtWidgets.QTextEdit(self.frame_4)
        self.patPhoneEntry.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patPhoneEntry.setFont(font)
        self.patPhoneEntry.setObjectName("patPhoneEntry")
        self.gridLayout_3.addWidget(self.patPhoneEntry, 0, 6, 1, 1)
        self.verifyHiBtn = QtWidgets.QPushButton(self.frame_4)
        self.verifyHiBtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.verifyHiBtn.setFont(font)
        self.verifyHiBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.verifyHiBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.verifyHiBtn.setObjectName("verifyHiBtn")
        self.verifyHiBtn.clicked.connect(self.verifyHealthInsurance)
        self.gridLayout_3.addWidget(self.verifyHiBtn, 1, 3, 1, 1)
        self.invoiceNoDisp = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.invoiceNoDisp.setFont(font)
        self.invoiceNoDisp.setStyleSheet("color:rgb(0, 85, 127);")
        self.invoiceNoDisp.setObjectName("invoiceNoDisp")
        self.gridLayout_3.addWidget(self.invoiceNoDisp, 1, 4, 1, 2)
        self.gridLayout_4.addWidget(self.frame_4, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_16)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setHorizontalSpacing(25)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableMeds = QtWidgets.QTableWidget(self.frame)
        self.tableMeds.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.tableMeds.setFont(font)
        self.tableMeds.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableMeds.setStyleSheet("QHeaderView::section {\n"
"                background-color: #00557d;\n"
"                color: white;\n"
"                font-weight: bold;\n"
"padding:5px;\n"
"            }")
        self.tableMeds.setAutoScrollMargin(0)
        self.tableMeds.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableMeds.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableMeds.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableMeds.setShowGrid(True)
        self.tableMeds.setWordWrap(False)
        self.tableMeds.setCornerButtonEnabled(False)
        self.tableMeds.setObjectName("tableMeds")
        self.tableMeds.setColumnCount(5)
        self.tableMeds.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 85, 125))
        self.tableMeds.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMeds.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMeds.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMeds.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMeds.setHorizontalHeaderItem(4, item)
        self.tableMeds.horizontalHeader().setCascadingSectionResizes(True)
        self.tableMeds.horizontalHeader().setDefaultSectionSize(180)
        self.tableMeds.verticalHeader().setDefaultSectionSize(45)
        self.gridLayout_2.addWidget(self.tableMeds, 0, 0, 1, 2)
        self.tableOrder = QtWidgets.QTableWidget(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.tableOrder.setFont(font)
        self.tableOrder.setStyleSheet("QHeaderView::section {\n"
"                background-color: #00557d;\n"
"                color: white;\n"
"                font-weight: bold;\n"
"padding:5px;\n"
"            }")
        self.tableOrder.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableOrder.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableOrder.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableOrder.setObjectName("tableOrder")
        self.tableOrder.setColumnCount(5)
        self.tableOrder.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrder.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrder.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrder.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrder.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrder.setHorizontalHeaderItem(4, item)
        self.tableOrder.horizontalHeader().setDefaultSectionSize(180)
        self.gridLayout_2.addWidget(self.tableOrder, 0, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QTextEdit(self.frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(1675515, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("PADDING:5PX;")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.insuranceDisp = QtWidgets.QLabel(self.frame_2)
        self.insuranceDisp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.insuranceDisp.setObjectName("insuranceDisp")
        self.gridLayout.addWidget(self.insuranceDisp, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.grandTotDisp = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.grandTotDisp.setFont(font)
        self.grandTotDisp.setStyleSheet("COLOR:RED;")
        self.grandTotDisp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.grandTotDisp.setObjectName("grandTotDisp")
        self.gridLayout.addWidget(self.grandTotDisp, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 1, 2, 1, 2)
        self.addBtn = QtWidgets.QPushButton(self.frame)
        self.addBtn.setMinimumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.addBtn.setFont(font)
        self.addBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.addBtn.setObjectName("addBtn")
        self.addBtn.clicked.connect(self.addToMyOrder)
        self.gridLayout_2.addWidget(self.addBtn, 2, 0, 1, 2)
        self.removeBtn = QtWidgets.QPushButton(self.frame)
        self.removeBtn.setMinimumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.removeBtn.setFont(font)
        self.removeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.removeBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.removeBtn.setObjectName("removeBtn")
        self.removeBtn.clicked.connect(self.delFromMyOrder)
        self.gridLayout_2.addWidget(self.removeBtn, 2, 2, 1, 1)
        self.proceedBtn = QtWidgets.QPushButton(self.frame)
        self.proceedBtn.setMinimumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.proceedBtn.setFont(font)
        self.proceedBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.proceedBtn.setStyleSheet("background-color:rgb(0, 85, 127);\n"
"COLOR:WHITE;\n"
"BORDER-RADIUS:5PX")
        self.proceedBtn.setObjectName("proceedBtn")
        self.proceedBtn.clicked.connect(self.placeOrder)
        self.gridLayout_2.addWidget(self.proceedBtn, 2, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "HOSPITAL MANAGEMENT SYSTEM"))
        self.label_19.setText(_translate("MainWindow", "ORDER MEDICINE"))
        self.label_28.setText(_translate("MainWindow", "DOCTOR NAME :"))
        self.label_26.setText(_translate("MainWindow", "PATIENT NAME :"))
        self.label_29.setText(_translate("MainWindow", "HEALTH INSURANCE CARD NO:"))
        self.label_27.setText(_translate("MainWindow", "PATIENT PHONE :"))
        self.verifyHiBtn.setText(_translate("MainWindow", "VERIFY"))
        self.invoiceNoDisp.setText(_translate("MainWindow", ""))
        self.label_3.setText(_translate("MainWindow", "QUANTITY REQUIRED :"))
        self.removeBtn.setText(_translate("MainWindow", "REMOVE"))
        self.proceedBtn.setText(_translate("MainWindow", "PROCEED"))
        self.tableMeds.setSortingEnabled(True)
        item = self.tableMeds.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "MEDICINE ID"))
        item = self.tableMeds.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MEDICINE NAME"))
        item = self.tableMeds.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "STATUS"))
        item = self.tableMeds.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "QTY AVAIL"))
        item = self.tableMeds.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "COST"))
        self.label.setText(_translate("MainWindow", "INSURANCE WAIVER:"))
        self.insuranceDisp.setText(_translate("MainWindow", "0%"))
        self.label_2.setText(_translate("MainWindow", "GRAND TOTAL:"))
        self.grandTotDisp.setText(_translate("MainWindow", "0"))
        item = self.tableOrder.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "MEDICINE ID"))
        item = self.tableOrder.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MEDICINE NAME"))
        item = self.tableOrder.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "QTY REQ"))
        item = self.tableOrder.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "COST"))
        item = self.tableOrder.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "TOTAL COST"))
        self.addBtn.setText(_translate("MainWindow", "ADD"))
import resources_rc
